### ISSUE TITLE
Teleportitis/Swimming Bug

### ISSUE THREAD

**Issue by tempestnano** [Chris-plus-alphanumericgibberish/dNAO#1]
This was filed under dNethack instead of dNAO previously.

My previous game, user Tempest. 9/23/2014, Turn 54120.
Swimming underwater, teleport prompt,
I don't recall if I teleported or not, I can't tell from my immediate message history.
I was then asked to "Dive underwater", but I was already under water from my previous dive, declined.
I got the message: "You swim to surface"; yet, I remain underwater with no breath clock.

Perhaps teleports should always spit you out above water.

**Comment by Chris-plus-alphanumericgibberish** [comment]
This was fixed ~1 year after being opened, but I can no longer find the commit that does it.

It was fixed by adding code to allmain.c that runs after every player action and monster action, and tests if the player is now out of the water as a result of that action.
