### ISSUE TITLE
buzz() does not accept die size?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1000]

**Comment by NeroOneTrueKing** [comment]
Yep. It recieves ndice (assumed to be d6s) or flat damage. If given flat damage, it uses that (not the dice).

Does this mean you want me to combine zhitm() and zhitu() and rewrite buzz()?

Just list the features you want in the comments below :P

**Comment by Chris-plus-alphanumericgibberish** [comment]
Yeah, I started merging them but then stopped because of all the stuff that happens outside of zhitm().

"More flexible handling for monster spells and breaths" is the number one forward-looking feature, I think. Current spell types are:
-Player-style fireball (non-damaging ray ending in an explosion)
-Ray
-Single-target ray (player-style magic missile spell)
-Enhanced ray (dragon breath/sleep breath attack)
Looking forward it might be neat to add SLASH'EM Sigil of Discharge-like effects
-Exploding ray (follows the same bouncing-off-walls rules as rays, but is a series of 3x3 explosions instead of a ray)

There's also varying rules as to what type of reflection is needed to reflect each type of effect.

And yeah, currently non-d6 damage dice are handled oddly, if not outright ignored (I *think* they're handle by rolling them in advance and passing in flat damage, which is :( ).

Currently, all effects are tangled together in annoying ways, for example tulanis and Oona use rays for cold and electricity spells but player-style fireballs for fire spells.  It would be good to be able to specify these effects in a flexible way, which probably means as arguments to buzz. I had thought about introducing extra object class-like IDs after the real ones to specify this, but that's probably not the best way to go :D

Examples:
-Baphomet will eventually pick up a cursed-blood breath attack that would use enhanced ray rules (maybe dragonbreath reflection).
-Morwell's AD_STAR ray should be non-reflectable but stop after it hits one target (single-target ray, non-reflectable).
-Oona and Tulani should use ray rules for everything
-Hellfire colossi should use some sort of blasting spell rules for their breath (maybe fireball, maybe exploding ray, dunno)
