### ISSUE TITLE
Things grudge on things they shouldn't

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1003]
Kiaransali drow grudge vs undead.

Undead on fixed levels like the castle.

Angels vs. Lamashtu.

Tagged work-in-progress related because I'm currently separating template-factions out into a separate field. Once the faction field is freed up for actual factions again, factions can be used to identify creatures that shouldn't grudge on each-other.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Templates are separate from factions now.

**Comment by NeroOneTrueKing** [comment]
The specific cases you've listed have been fixed in dev.

Implementing more thorough factions (consider looking at ToME?) would be a rather large feature worthy of its own design doc.

**Comment by Chris-plus-alphanumericgibberish** [comment]
To explain why I unlinked this issue from the pull request: Lost house drow are actually different than Kiaransali drow (she's the silver ringed-hand symbol), and if you somehow managed to get Lamashtu around regular angels (or her angels around regular angels) they **should** grudge vs. each other.
