### ISSUE TITLE
Vampire Rogues allowed to two-wep

### ISSUE THREAD

**Issue by Somlia** [Chris-plus-alphanumericgibberish/dNAO#1010]
Would it be possible for Vampire rogues to have 2wepping? If it's a balance issue I would understand, just curious.

**Comment by NeroOneTrueKing** [comment]
Considering that two-weaponing isn't the go-to DPS in dnethack it is in vanilla, I think relaxing Vampires' twoweapon restriction for all roles would be reasonable.
And it would have the additional benefit of not needing special-casing for anachrononaut vampires to be allowed to twoweapon.
