### ISSUE TITLE
Travel command can get stuck in infinite loops

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#1015]
Not sure how to reproduce yet, but we keep getting reports of this every now and then.

**Comment by Chris-plus-alphanumericgibberish** [comment]
bubbles had another observation.  She observed an infinite travel loop caused by a narrow gap that she couldn't actually fit through.

https://media.discordapp.net/attachments/384784727774724121/741266554112573530/unknown.png?width=910&height=664

**Comment by bubblehack** [comment]
fyi it is a he 👍

**Comment by NeroOneTrueKing** [comment]
Hopefully fixed by 5f44ed15e0af00aeac812e5a14e4b899e88da9bd? Marking as such.

Edit: nope
