### ISSUE TITLE
altmeta option

### ISSUE THREAD

**Issue by transcendreamer** [Chris-plus-alphanumericgibberish/dNAO#1034]
I would like to suggest adding altmeta option for ALT key support in ssh terminal sessions.

**Comment by RikerW** [comment]
For me this is a terminal option already - what terminal are you using?

**Comment by transcendreamer** [comment]
My bad, it was something with my settings, now I have completely reinstalled Putty, now everything is working alright, sorry for bothering you!

**Comment by RikerW** [comment]
No worries, glad I was able to help.
