### ISSUE TITLE
Samurai discoveries crash

### ISSUE THREAD

**Issue by AmyBSOD** [Chris-plus-alphanumericgibberish/dNAO#105]
This code in objnam.c function obj_typename():

`if (Role_if(PM_SAMURAI) && iflags.obscure_role_obj_names && Alternate_item_name(otyp,ObscureJapanese_items))
		actualn = Alternate_item_name(otyp,Japanese_items);`

causes a segfault if a samurai tries to view the names of certain items because it incorrectly compares the item to the entry in "Japanese_items" instead of "ObscureJapanese_items" (copy and paste bug).

**Comment by RikerW** [comment]
[fixed](https://github.com/Chris-plus-alphanumericgibberish/dNAO/commit/90f20f5b623ba549a83033fa23fbe4b95c01681c#diff-8792895241cf9edd8b237d6d1f6b667a)

**Comment by AmyBSOD** [comment]
yeah it's fixed now, thanks
