### ISSUE TITLE
Octet martial aids don't get the bonus damage

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#1052]
```c
if (obj && (otyp == LIGHTSABER || otyp == BEAMSWORD || otyp == DOUBLE_LIGHTSABER) && !litsaber(obj)){
	spe_mult = 1;
	if(obj->oartifact == ART_FLUORITE_OCTAHEDRON){
		ocn = 1;
		ocd = 8;
	} else {
		ocn = 1;
		ocd = 2;
	}
	bonn = 0;
	bond = 0;
}
```

This implies that a lightsaber with the octet in it, even when unlit, still does `1d8+spe` (presumably with explody dice too but that's less important here). However, xhity.c checks `martial_aid` and immediately jumps to the unarmed punching, and doesn't treat the saber as its own weapon, so it never gets the octet damage bonus. Intentional? 

Easiest solution I can think of is to add the damage bonus of the unlit saber directly, rather than adding `d4+enchantment` separately. This would require the entry in weapon.c to check the otyp to set `ocd` but that's probably doable.

**Comment by NeroOneTrueKing** [comment]
Fixed via monkey's paw.
