### ISSUE TITLE
There seems to be some issue with vampires draining inventory items

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1075]
See here for a screenshot from microlance https://images-ext-2.discordapp.net/external/bKyG6UHPE3LK-CJ1zKvvdolx38uilvoyNXChO_lPXrc/https/forumbilder.com/images/2020/08/08/wut.png?width=735&height=664

`The titanothere vampire drains a wide conical hat (being worn)`, over and over again.

**Comment by NeroOneTrueKing** [comment]
Probably fixed by #1028. Adding the fixed-in-dev tag; we can remove it and reconsider the problem if we can reproduce it on dev.
