### ISSUE TITLE
Checking mons[egg->corpsenm] is unsafe

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#1155]
Eggs can have `corpsenm == -1` to signify they are a bland generic egg with no related permonst.

**Comment by NeroOneTrueKing** [comment]
Partly addressed by #1160.

@demogorgon22 What other bad eggs are there?

**Comment by amateurhourrrr** [comment]
additional case addressed by #1174

**Comment by NeroOneTrueKing** [comment]
I'll mark this as fixed in dev, but we may still eventually see more harder-to-find eggs
