### ISSUE TITLE
read after free when light source monster explodes

### ISSUE THREAD

**Issue by amateurhourrrr** [Chris-plus-alphanumericgibberish/dNAO#1173]
When a light source monster moves and explodes there's a read after free when recalculating vision

in vision_recalc it calls do_light_sources which calls get_mon_location on a freed monster

if this is part of the same moveloop, as in vision has to be recalculated when a previous explody monster has died, this will read data from the freed monster

Might be worth seeing how vanilla handles it, perhaps it doesn't free the monster and just flags it

**Comment by NeroOneTrueKing** [comment]
THANK YOU.
THIS LET ME REPRODUCE AN LS BUG.
`maybe_write_ls: no id!`
