### ISSUE TITLE
Amor encumbrance needs to be looked at

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1191]
Armor encumbrance is *mostly* BS, but despite the names light/medium/heavy is actually more about how flexible a suit of clothing is rather than strictly about its size.

So the human noble clothing **was** supposed to be "heavy," on the grounds that it's tailored or something and hard to move around in. But, perhaps it should be "medium" instead.

Consort suits should be heavy because they have corsets.

Droven armor generally could maybe drop an encumbrance level, given how much a pain it is to keep around, especially now that high elven plate exists and is medium instead of heavy. It's *possible* that anything made of shadowsteel could drop a level of encumbrance? I dunno why high elven plate is less encumbering. Possibly it should be ruled a default property of mithril, possibly it should be ruled a consequence of superior design.

dNh currently inherits a misunderstanding of plate armor vs. chain mail from D&D: If I'm understanding right, a good set of plate is both less encumbering and much more protective than chain.

**Comment by NeroOneTrueKing** [comment]
I may look into making mithril and shadowsteel armor 1 tier lighter, as a material thing. I'll have to check all the basic armors to make sure it doesn't make elven/dwarvish mithril coats lesser than a "mithril ring mail" or something.

**Comment by NeroOneTrueKing** [comment]
Update: leaning towards "no".

Banded mail (3AC/3DR medium armor weighing 175 aum) would become mithril banded mail (4AC/4DR light armor weighing 87 aum). Which is better defense than either elven or dwarvish mithril coats, albeit heavier.
