### ISSUE TITLE
IMA is off when thrown

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1311]
I'm guessing this is because it doesn't have a location when in the air.

Fixing this may be a pain.

**Comment by NeroOneTrueKing** [comment]
Yes. Both `litsaber()` and `dmgval_core()` use `get_obj_location()` for IMA. Wisely, `get_obj_location()` gives (x=0,y=0) for objects that with `obj->where==OBJ_FREE`.

We may need to totally re-write how IMA decides how lit it is.
