### ISSUE TITLE
corridor/lit corridor colors are reversed

### ISSUE THREAD

**Issue by k21971** [Chris-plus-alphanumericgibberish/dNAO#1325]
See this screenshot - https://www.hardfought.org/phpBB3/gallery/image/2562/source - you can see that lit corridor vs unlit, the colors are reversed.

drawing.c, lines 244 and 245:
`        {'#', "corridor",       C(CLR_GRAY)},   /* dark corr */`
`        {'#', "lit corridor",   C(CLR_BLACK)},  /* lit corr (see mapglyph.c) */`
The colors there should be the other way around.

**Comment by NeroOneTrueKing** [comment]
@k21971 is it fixed now?

**Comment by k21971** [comment]
Yes, this will do it. Thanks!
