### ISSUE TITLE
Autotarget polearms would make polearm applied usage more viable + QoL

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1380]
Both Fiqhack, and apparently vanilla 3.6 implement autotarget polearms which select "the best target" as the cursor location when applying a polearm. This would save a lot of time in dnh for players using polearms and potentially make players more willing to use them. Fiqhack, on top of this binds "f"/dofire to automatically applying a polearm to "the best target." I am more dubious about this being a safe change to make, but it could lead to more usable polearms if worked in properly.

**Comment by NeroOneTrueKing** [comment]
Chris has added an alternative polearm mode that allows `a`-`a`-`a` to `a`pply item `a` (your polearm adjusted to 'a') at the first monster in range (`a`), which IMO has filled this need well enough, or even better than autotarget (which would be `a`-`a`-`.`). Optional binding of polearms to `f`, as FIQhack does, I think is beyond our goals at this time (we don't quiver spells either).
