### ISSUE TITLE
Foocubi clockwork winding can lead to unexpected deaths

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#1390]
They wind you `0.8+rn2(5)` times what you ask for... AKA max of 4.8 times. If you ask for 1 food ration's worth (80 turns), you can instead get as much as 3840 turns, which is probably enough to kill you, unless you have a mainspring upgrade *and* are Waning or hungrier (or 2+ mainspring upgrades).

**Comment by Chris-plus-alphanumericgibberish** [comment]
Adding bug minor: *Pretty* sure that was meant to be 80%->120%, not 80%->240%, ie, (8+rn2(5))/10

**Comment by NeroOneTrueKing** [comment]
That makes sense, thanks Chris.
