### ISSUE TITLE
Marilith arms can use weapons not normally two-weaponable (but offhandable)

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#1411]
As-is, it only checks bimanual/is a weapon/etc. for the player- aka, it has to be a valid weapon for two-weaponing at all. However, no weight limits are placed. This lets the player stack some really absurd one-handed things that probably aren't kosher in terms of balance, even though this does require you committing to that much weight in open inventory & polymorphing into a marilith/binding miska.

Note: I mean this only with youagr, monsters it's fine and all that jazz.

**Comment by NeroOneTrueKing** [comment]
Current rules in devel:
```
if ((otmp->oclass == WEAPON_CLASS || is_weptool(otmp)
	|| (otmp->otyp == CHAIN && pa->mtyp == PM_CATHEZAR)
	)																	// valid weapon
	&& !(otmp->oartifact && !always_twoweapable_artifact(otmp))			// ok artifact
	&& (!bimanual(otmp, pa) || pa->mtyp == PM_GYNOID || pa->mtyp == PM_PARASITIZED_GYNOID)// not two-handed
	&& (youagr || (otmp != MON_WEP(magr) && otmp != MON_SWEP(magr)))	// not wielded already (monster)
	&& (!youagr || otmp->owt <= max(10, P_SKILL(P_TWO_WEAPON_COMBAT)*10))// not too heavy
	&& (!youagr || (otmp != uwep && (!u.twoweap || otmp != uswapwep)))	// not wielded already (player)
	&& !(is_ammo(otmp) || is_pole(otmp) || is_missile(otmp))			// not unsuitable for melee (ammo, polearm, missile)
	&& !otmp->owornmask)												// not worn
```
These do include weight limits on the offhand weapon.
