### ISSUE TITLE
The shard from morgoth's crown can be polymorph

### ISSUE THREAD

**Issue by amateurhourrrr** [Chris-plus-alphanumericgibberish/dNAO#1426]
Happened in Demo's game today - the ring was an iron polymorph ring

Perhaps something could be amiss in find_good_iring (such as twisted rings not being guaranteed to exist or the checks being wrong after a refactor?)

**Comment by NeroOneTrueKing** [comment]
Not reproducing this -- I hacked o_init to shuffle rings until iron was polymorph, and chaos3 correctly made the Shard based on the twisted ring.

**Comment by amateurhourrrr** [comment]
Was that just shuffling them or did it re-roll appearance randomisation entirely? I hear twisted rings might not exist as an appearance at all

**Comment by NeroOneTrueKing** [comment]
Recalling the function that does appearance shuffling, `shuffle(RIN_ADORNMENT, RIN_PROTECTION_FROM_SHAPE_CHAN, TRUE)`.
All rings of polymorph were iron rings.

Unlike scrolls and wands, there are no excess appearances for rings -- there is a twisted ring in all games.

**Comment by NeroOneTrueKing** [comment]
Apparently this was a game from 3.18 -- it has since been fixed.
