### ISSUE TITLE
Monsters with keys will kick down doors with the key instead of unlocking it

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1428]
Monsters with keys will kick down doors with the key instead of unlocking it. I thought this was fixed a while ago and the patch was on hdf, buy my pet myrmidon ypolochagos was locked in a room with a key, picked it up, and used it to kick down and destroy the door holding him in.

**Comment by NeroOneTrueKing** [comment]
Just had a pet successfully unlock and open a locked door using a key, and looking through the monmove code it looks like those should be handled correctly too.

**Comment by NeroOneTrueKing** [comment]
Can't reproduce, and when do monsters even carry keys? If we start being able to reproduce it, then let's reopen this.
