### ISSUE TITLE
Various effects don't interrupt waiting/eating/etc.

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#1485]
At least two effects don't properly interrupt a multiturn action:

- Tensa Zangetsu bone-grinding (discovered via eating an orange dragon corpse)
- Mental blasts (discovered via timed waiting & a mind flayer's blasts)

**Comment by NeroOneTrueKing** [comment]
Fixed these two specifically, in #1625 and commit#ff65cd6
