### ISSUE TITLE
Ahazu Acererak Abduction?

### ISSUE THREAD

**Issue by Wikid-VoR** [Chris-plus-alphanumericgibberish/dNAO#1497]
Playing dNethack 3.20.20 at hardfought.org as vor, with Ahazu bound.
Final fight at upstairs, suddenly Acererak is not there any more, dropped Bell of Opening.  No messages.  
But Quest is still not complete, Pen of the Void still has only one blade.  
I can't get ^P to work on hardfought.org, so can't check what happened.  
Thinking Ahazu abducted Acererak, so quest completion wasn't logged.
Now game looks unwinnable.
Help!  Thanks!

**Comment by NeroOneTrueKing** [comment]
That seems like the culprit, yes. Sorry, I think your game is now unwinnable.

**Comment by Wikid-VoR** [comment]
Can't say I wasn't warned about Ahazu! Time to climb the stairs ...
