### ISSUE TITLE
Bug sighting: artifact spellbooks

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1501]
A book of secrets claiming to be the Book of Lost Names was sighted whose actual oartifact ID was set to the Book of Infinite Spells (but had been initialized as though it was the BoLNames).

**Comment by NeroOneTrueKing** [comment]
Successfully reproduced.

Calling itself BoLN, actually Necronomicon.
