### ISSUE TITLE
tip/icebox/shop interaction

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1533]
From Demo:

also, tipping an icebox in a shop doesnt work properly
i got paid for each corpse and didnt even have to pay for him, but then they were his property still
it was wahck

oh fuck
https://pastebin.com/raw/wCwy9QRi
#tip is totally fucked
this was while off level from the corpses i tipped
alright thats like 2 #tip bugs in one

^^ coming back on level to the level with the tipped corpses with timers prevented the crash from happening when the timer ran out

**Comment by NeroOneTrueKing** [comment]
Timers were responsible for the crash, and have been fixed.
All that remains is the hippity hoppity shopkeepers corpses were your property bug.
