### ISSUE TITLE
Statues of unique monsters no longer seem to animate properly

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1534]
Tested with statues of Great Cthulhu and the Adamach on the Sum of All level.

Unique monster statues should animate as a doppelganger in the form of the unique monster depicted in the statue. Instead, they animated in the form of a player monsters (probably a random roll of the doppelganger form list).

**Comment by Chris-plus-alphanumericgibberish** [comment]
After reproducing twice perfectly, it now doesn't reproduce at all >_<

Maybe this was just a rash of doppelgangers immediately shapeshifting?

**Comment by NeroOneTrueKing** [comment]
I think it's that the doppelgangers shapeshift 1/6 turns, not on a timer/cooldown (`timeout_problems()`, mon.c). Not a bug, unless we want to poke that.
