### ISSUE TITLE
Zombies pick up items

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1535]
Despite the fact that they have mindless added and all item pickup MT flags removed, they still pick stuff up.

This suggests some problem with how that code works

**Comment by NeroOneTrueKing** [comment]
They'll pick up equipment if they can use it (`is_armed()`), but not greedy things like gold, gems, or magic items. Should zombies receive the `notake` flag as well, so that they can't pick up anything?
