### ISSUE TITLE
DEADMONSTER should include "and the monster is not the PC"

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1564]
The player character doesn't use the youmonst hp field, so they always register as dead and need to be excluded from the DEADMONSTER check.

Marked "complex" because removing the existing != youmonst checks sounds like a pain in the neck.

**Comment by NeroOneTrueKing** [comment]
268 results in 43 files for DEADMONSTER, shouldn't be that bad :)
