### ISSUE TITLE
Kicking while riding a steed to make it gallop crashes

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1609]
Reported by post163 the legendary rider. Tested locally with a human knight just mounting the starting pony and kicking.

Program received signal SIGSEGV, Segmentation fault.           
0x00000000086e04b8 in kick_steed () at src/steed.c:441
441                             newsym(u.usteed->mx, u.usteed->my);
(gdb) bt
#0  0x00000000086e04b8 in kick_steed () at src/steed.c:441
#1  0x0000000008212235 in dokick_core (dx=0, dy=0) at src/dokick.c:559
#2  0x000000000821207b in dokick () at src/dokick.c:536
#3  0x0000000008163a66 in rhack (cmd=0x8c57a40 <in_line> "\004") at src/cmd.c:6487
#4  0x000000000807ba0b in moveloop () at src/allmain.c:2794
#5  0x00000000088d571a in main (argc=4, argv=0x7ffffffee198) at sys/unix/unixmain.c:296

**Comment by Chris-plus-alphanumericgibberish** [comment]
No need for a newsym call at all.
