### ISSUE TITLE
Scatter() does not handle shop inventories

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1623]
'Keepers didn't care if a mine destroyed shop inventory.

In the current version, they mind some things but still don't mind if a breakable object *thrown* by an explosion shatters when it lands (xhity unowned projectile code needs adjusting to handle this, I think).

**Comment by NeroOneTrueKing** [comment]
Not just projectile code; `scatter()` doesn't use projectiles except for hitting monsters. Instead, it directly calls `breaks()` when scattering objects about, which is considered not the hero's fault.

Unless vanilla shopkeepers [somehow] care if your mine destroys their shop inventory, I'd call this one not-a-bug.

Edit: Just checked devel commits and I see you recently made `scatter()` costly.

**Comment by NeroOneTrueKing** [comment]
Looks like you just need to add the `shkp` sections to the rest of `scatter()`. `hmon_with_unowned_obj()` does let the caller know if the unowned obj was destroyed; check whether the obj-pointer pointed to by the obj-pointer-pointer passed to hmon is null.
