### ISSUE TITLE
Earthquake monster spell can still be cast on Binder goal level

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1715]
In the past aligned priests were known to cast earthquake and destroy altars requiring thought travel to make the game winnable.
I believe this was fixed by making earthquake uncastable on this level? Perhaps only for aligned priests?

I had this occur on the binder goal level near the altars and believe it isn't intended to be possible.
"The silver star bearing unearthly drow casts a spell at the Tulani Eladrin of Diana!  The entire dungeon is shaking around you! "

**Comment by NeroOneTrueKing** [comment]
Not a bug, the fix was to protect the altars from destruction by earthquake (including drums of earthquake)
```
		  case ALTAR :
			if (Is_astralevel(&u.uz) || Is_sanctum(&u.uz) || (Role_if(PM_EXILE) && Is_nemesis(&u.uz))) break;

			if (cansee(x,y))
				pline_The("altar falls into a chasm.");
			goto do_pit;
```
