### ISSUE TITLE
Monsters detected with Numina are counted as 'seen' cross map

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1716]
Also I think they interrupt multi turn actions even if they are far away and the player gets far more messages about what they are doing than monsters sensed by sting or something.

**Comment by NeroOneTrueKing** [comment]
I don't see any reason how Tenebrous detection would act differently than Sting detection; they both fall into `MATCH_WARN_OF_MON`.

**Comment by NeroOneTrueKing** [comment]
Not reproducing any ability to unexpectedly interrupt multi-turn actions, either

**Comment by NeroOneTrueKing** [comment]
And, scaring all monsters on level happens regardless of your ability to detect them:
```
	/*Scare hostile monsters on level*/
	{
		struct monst *tmpm;
		for(tmpm = fmon; tmpm; tmpm = tmpm->nmon){
			if(!tmpm->mpeaceful){
				monflee(tmpm, 77, TRUE, TRUE);
			}
		}
	}
```

**Comment by demogorgon22** [comment]
It could be related to some other spirit I had bound at the same time, I don't know. Somehow something was allowing me to see certain monsters even though they were across the map and I should have been able to only sense them. This is with numina bound and infravision.

**Comment by NeroOneTrueKing** [comment]
Aha. This is all Numina.
