### ISSUE TITLE
Wages of Sloth OP

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#1734]
Pls nerf.

Less the 1 turn used crushing the wage, uncursed gives 3 turns, and cursed gives 8.
These are too much, especially when chained.

I think the following would be fair:
Uncursed: 1 move    (aka 2 - 1)
Cursed:     3 moves  (aka 4 - 1)

**Comment by Chris-plus-alphanumericgibberish** [comment]
Added this nerf to local dev.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Oops >_< (we usually don't close until the next version goes live)
