### ISSUE TITLE
Room number 44 out of 40? Program in disorder - you should probably S)ave and reload the game.

### ISSUE THREAD

**Issue by transcendreamer** [Chris-plus-alphanumericgibberish/dNAO#1738]
Good day, dev team, today I've seen this message (subj) when I tried to enter a shop being invisible myrkalfr anachrononaut, and one more message: "This shop appears to be deserted." - while it was obviously not deserted. Other shops I tried to enter generate the same messages.  Version v3.21.1 (dNAO git 79554566) at hardfought server.

**Comment by Chris-plus-alphanumericgibberish** [comment]
It's a dumb bug created when I was trying to fix another dumb bug. It should be fixed in the latest version of the source.

**Comment by transcendreamer** [comment]
Now everything is OK at hardfought server with version v3.21.1 (dNAO git a180d141) build 2021-09-25 -- and I think the issue may be closed -- thank you for the update!
