### ISSUE TITLE
Hell-p summoned from demon attacking displacement image

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1740]
"Lungorthin strikes at your displaced image and misses you!" he still summoned hell-p... is that supposed to be possible?

**Comment by Chris-plus-alphanumericgibberish** [comment]
Does the help arrive centered on you?

This does seem like it could cause problems, confused monsters have been known to attack squares that are no where near the player.

**Comment by NeroOneTrueKing** [comment]
It is always centered on the player; fixing.
