### ISSUE TITLE
Killing an acid paraelemental by creating water under it may cause a dmonsfree impossible

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1744]
"You are standing at the top of a stairwell leading down!  The acid paraelemental explodes.  dmonsfree: 1 removed doesn't match 2 pending  Program in disorder - you should probably S)ave and reload the game." 
I assume there was an acid paraelemental in the zone that got turned into water after doing the invocation and it died too hard or something? Not very sure.

**Comment by Chris-plus-alphanumericgibberish** [comment]
I see it. Exploding Acid Paraelementals always double-die.
