### ISSUE TITLE
Illuminated template monsters can revive with their halo after being cancelled

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1803]
Not sure if this is a bug but this is pretty unintuitive for players who have learned how the blessed's halo and cancellation interact.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Also made it work vs. fractured and uvuudaum. Cancellation continues to be buffed!

1409ee7d74bba7555b842cd4b65e6fd1e55e3d40
