### ISSUE TITLE
Crash in devel-3.21.2 in m_initweap passing null obj ptr to set_material_gm

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1820]
![image](https://user-images.githubusercontent.com/8377693/147386915-9f15e37f-2261-44d3-8f59-cda92d7c56fd.png)
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/devel-3.21.2/src/makemon.c#L1504
In some cases it can fail to make the kite shield which results in set_material_gm being called with a null obj ptr which leads to the crash.

**Comment by demogorgon22** [comment]
Honestly I think theres a lot of unguarded mongets() into null obj into attempt to deref left and this whole thing should probably be audited further.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Right zombies :(

All otmp = mongets() should be safe now. 2438fbe1cb2cfe484d690acddf8fd91b4c88e8e8
