### ISSUE TITLE
Deep one wall charges on ana home can end up off map

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1822]
![image](https://user-images.githubusercontent.com/8377693/147418386-c411f8d4-cb64-49af-8d67-64a59bd3e213.png)
on an ls with x =6 y=21 from a stick of dynamite on ana home level, presumably a result of deep one charges.

**Comment by Chris-plus-alphanumericgibberish** [comment]
33c2209955e3fd430a39540e78cce2f35600fcdd
