### ISSUE TITLE
Hod sephirah attack against me while wielding potion crashed

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1836]
![image](https://user-images.githubusercontent.com/8377693/148661510-1fd45b80-9743-4004-9884-95860f2fb070.png)
Not sure if this is replicable but I don't think the logic takes into account the edge case of how things are when hod attacks or maybe other mirror attacks happen?

**Comment by NeroOneTrueKing** [comment]
Easy to reproduce. Going to be hard to fix. Yuck

Edit: nevermind, not so bad.
