### ISSUE TITLE
Creating player monsters as part of level definition des files can crash the game if extinct

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1839]
![image](https://user-images.githubusercontent.com/8377693/148662269-f8d28f3e-56b2-434b-96ef-f8c47f199c2a.png)
The way that the code handles making extinct monsters from des descriptions it sets pm to null ptr and calls makemon with it. This is fine but for player monsters and roamers, their functions can't handle a null ptr pm and the game crashes. I think.
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/4d5bac716ce209243f6349d973f3bc274791deaf/src/sp_lev.c#L872-L878
The comment assumes a random monster will be created if pm is null, but later on the code pass the null pm to either mk_roamer, mk_player, or makemon, two of which crash when given a null pm.
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/4d5bac716ce209243f6349d973f3bc274791deaf/src/sp_lev.c#L909-L913

**Comment by Chris-plus-alphanumericgibberish** [comment]
Should be fixed by f7d7db34539dbca41d7a32263d09571ad862ba21 (which fixes intermediate state e4e6ff14e900b80c60c45a327dbd9533508e243c)
