### ISSUE TITLE
Necronomicon secrets of war and killing has handling for teaching martial arts but won't actually ever do it

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1860]
Looking at the code, it is busted because it isnt a whitelisted skill beyond last weapon. Attempting to train martial arts with it will always fails.

**Comment by demogorgon22** [comment]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/3f082e2c39fac91e6c38ba729ebe8839b82961c3/src/artifact.c#L9945
This is the bad part

**Comment by Chris-plus-alphanumericgibberish** [comment]
8c1ccca51774adeba0c0300a8c315702dafe958d
