### ISSUE TITLE
Firework carts can cause explosions that explode and wake_nearto off map

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1862]
![image](https://user-images.githubusercontent.com/8377693/149832537-95fcbf77-8ffd-447b-843a-b1178e401a39.png)
Glad the wake_nearto sanity check helped find this.

**Comment by Chris-plus-alphanumericgibberish** [comment]
2b14bf4b114e64cf7d504830211cccca495caaf1
