### ISSUE TITLE
When a set of Fluorite Octet or Fluorite Octahedra is thrown upwards,only one Fluorite Octahedron falls back

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#1877]
> You throw the Fluorite Octet.  The uncursed Fluorite Octet hits the ceiling, then falls back down towards your head.
The Fluorite Octahedron hits you!

**Comment by NeroOneTrueKing** [comment]
Fixed by #1878
