### ISSUE TITLE
Can't create desecrated weapon by reading scroll of consecration

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#1880]
It's said
>  If read while confused, applies the consecracted or desecrated oprop to your equipped weapon, based on the scrolls beatitude

in wiki, but i found it only create consecracted no matter the BUC of the scroll

**Comment by NeroOneTrueKing** [comment]
Hi Baoliejuan, thank you for the report, but I'm not able to reproduce this bug. Reading a cursed scroll of consecration while confused is applying 'desecrated' to the wielded weapon as intended. Reading an uncursed or blessed scroll of consecration while confused is apply 'consecrated' as intended. Can you check that you are playing on dnethack version 3.21.2?

**Comment by baoliejuan** [comment]
Sorry I'm not playing on 3.21.2 cause have some problem building it, but i tested it in 3.20.0 to 3.21.1 and all got the same issue. Maybe it's just fixed in latest version.

**Comment by baoliejuan** [comment]
Yes it's

**Comment by NeroOneTrueKing** [comment]
The feature addition was made in 3.21.2, yes.
