### ISSUE TITLE
Monster revivification picking up all items on the ground when reviving can cause ball chain crashes

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1883]
A troll reviving on your ball and likely chain will force it to pick it up. Balls and chains are not allowed for their "where" to be a monster's inventory so attempting to move will cause a crash.  You can probably abuse this to move magic chests as well but I haven't tried.

**Comment by NeroOneTrueKing** [comment]
Chris plz

**Comment by Chris-plus-alphanumericgibberish** [comment]
80b1806e5d081d4452fa26fec43d633e72a86ab2
