### ISSUE TITLE
Pets can untame in dog_move which can lead to attempting to access non existent dog mextra substructs

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1885]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/3dfc134f16aff38d51e4716a6a8cb73d5d0708d6/src/dogmove.c#L1013-L1018
Pets untaming in dogmove can cause a crash when it later tries to read the mextra substruct it assumes exists. I figure this function should probably return after untaming or something. Someone should make sure there are no other cases where it is possible for the dog to untame without the function returning after (perhaps via some mvm combat idk).

**Comment by Chris-plus-alphanumericgibberish** [comment]
76019cf5935e987d5fe31e614405aeee4d287f01
