### ISSUE TITLE
Grue level sack fails to generate properly

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1889]
I don't know what is going on with it. I got a weird crash while fuzzing but then whenever I load the level in wizard mode to try and replicate I get impossibles instead which is weird. I'm sure it is just bad des file syntax or something probably.
![image](https://user-images.githubusercontent.com/8377693/158415506-77259c98-7a72-49d1-ae49-53ddffef53a7.png)
The container it is trying to add it to has a cobj ptr of 0x601

**Comment by amateurhourrrr** [comment]
needs to be CONTAINER rather than OBJECT for the sack I think
