### ISSUE TITLE
Potions of starlight can still lose their light source when diluted which causes an end_burn impossible from water_damage

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1891]
![image](https://user-images.githubusercontent.com/8377693/159009854-39900345-2364-4b46-88aa-a4feeb92f6a9.png)
Despite the changes made here  https://github.com/Chris-plus-alphanumericgibberish/dNAO/issues/1835, this still managed to happen again somehow.

**Comment by NeroOneTrueKing** [comment]
😱

**Comment by NeroOneTrueKing** [comment]
I'm guessing the source of this was some potion alchemy creating a random potion which happened to be Starlight, which wouldn't correctly create the lightsource. I'll do something about this eventually but I think it's safe to ignore for now.

**Comment by NeroOneTrueKing** [comment]
lol I had noticed this before, made a fix, then broke the fix
