### ISSUE TITLE
Meteor Drive dice use dbon number of dice which can be negative

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1892]
![image](https://user-images.githubusercontent.com/8377693/159021131-72cdc698-74fd-483b-8b5c-f9410467ef6c.png)

https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/e34dbd02be9dc519f377169778186a0e71d4cc46/src/xhity.c#L17224
dbon can return a negative number if your strength sucks enough.

**Comment by Chris-plus-alphanumericgibberish** [comment]
e94eb581c2626f44355a73a7bdfa589345a50833
