### ISSUE TITLE
Digging off the map while inside an engulfer at the edge of the map can cause a crash

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1903]
![image](https://user-images.githubusercontent.com/8377693/160262907-79f4b3ef-a2df-405b-9cc6-316f3168fbd6.png)
This one is cool. https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/fae6bc5818e55a680ef94e6e090c8303495358ec/src/dig.c#L1933 in use_pickaxe2 attacks the stuck guy but in attack2 xattacky actually gets called with your position modified by udx and udy
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/fae6bc5818e55a680ef94e6e090c8303495358ec/src/xhity.c#L216
Easy enough to replicate, just get engulfed at the bottom of the screen and dig towards the bottom line with a pick.

**Comment by Chris-plus-alphanumericgibberish** [comment]
commit 9414b3a48017c73981adca5b3893b35f41fb5519
