### ISSUE TITLE
Confusion/Stun resistance and clear thoughts don't show up on artifact inspection

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1910]
![image](https://user-images.githubusercontent.com/8377693/161439663-d9f99a84-bf45-4831-bd1d-5ec0fdf8a1e9.png)
It doesn't show that the item conveys those properties when carried.

**Comment by NeroOneTrueKing** [comment]
![image](https://user-images.githubusercontent.com/28197216/166119338-e68c7f48-d719-4da2-9c58-19ce1a44d325.png)
