### ISSUE TITLE
C343-384 Cutting a level 0 long worm in half may lead to a worm with 0 HP

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1911]
![image](https://user-images.githubusercontent.com/8377693/161781400-cae5dc2e-89ce-42a4-a944-c71f66c38c30.png)
I don't know if it is the same cause but it seems to be this bug.
![image](https://user-images.githubusercontent.com/8377693/161781653-ac9e8a93-4a59-4ba7-a8ba-489d273565f5.png)
m_lev is 0

**Comment by amateurhourrrr** [comment]
if it's related, I ported vanilla's fixes for worms to slashem here: https://github.com/k21971/SlashEM/commit/b5bf8d6ffd49b20764ec78b5a2f2bec20422e6df
