### ISSUE TITLE
Horror AD_DRIN attacks can spawn with ridiculous dice

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1912]
Balance concern.
AD_DRIN dice, used to roll amount of int removed, are generally low and reasonable as it kills you in a way that hits through life saving. Because of this, there should be some prevention from horrors potentially spawning with attacks that can instakill you through all your lifesaving sources, especially because these can be ranged attacks. Randomly getting oneshotted through all your lifesaving sounds no fun to me.

**Comment by Chris-plus-alphanumericgibberish** [comment]
From examining the code it does look like AD_DRIN uses the generic special attack dice, which are
```C
			attkptr->damn = 1 + d(1, 2) + rn2(2)*rn2(3);	/* 2 -  5, trailing right */
			attkptr->damd = rn2(5 - attkptr->damn) * 2 + 6;	/* 6 - 10, by 2s */
```
So you can easily get one-shotted by int-drain horrors.
