### ISSUE TITLE
Killing blasphemous lurker can be considered murder

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1914]
"You kill the blasphemous lurker!  You murderer!" When killing with a mind blast without ever entering its temple. It was hostile and I never attacked it so I don't know why it was murder.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Probably a result of not having MT_HOSTILE, plus dodgy logic on how murder is determined.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Should be fixed by 12f985884ad8a635ced2c68becd32d0ff68b43df
