### ISSUE TITLE
Monster AoE explosive spells can explode off map

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1921]
![image](https://user-images.githubusercontent.com/8377693/162844903-9eab3531-3c75-4247-b6e8-4178fbd46536.png)
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/b843cd230990ff75f99ab66f4f64f8641fe4dc5e/src/mcastu.c#L3648
This has got to be very old.

**Comment by Chris-plus-alphanumericgibberish** [comment]
commit ba92e4d943a9daaaf70ea8bc45629500c73c8248
