### ISSUE TITLE
Madman crowning gifts botched

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1922]
Lawful crowning gives the sickle, which seems to work as intended.
Neutral crowning gives the spear of peace, which is a chaotic weapon.
Chaotic crowning gives Stormbringer.
It is currently impossible to get the war-helm of dreaming as far as I can tell

**Comment by Chris-plus-alphanumericgibberish** [comment]
Spear of peace being a chaotic weapon has already been fixed, and Stormbringer instead of the war helm is a purposeful placeholder due to war helm not being implemented.
