### ISSUE TITLE
Earthquake destroying high altar to moloch MAY prevent EP from angering when entering his temple

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1924]
If the high priest sanctum is desecrated before you enter it by an earthquake spell destroying the altar, the code that angers the elder priest upon entering the temple never is triggered and the elder priest remains peaceful.
![image](https://user-images.githubusercontent.com/8377693/164340926-b9bf9d53-5051-4410-91d3-2e5db3046497.png)
Warning: This is all speculation I don't actually know that this is what happened, but it is a safe bet and makes sense without looking at things and testing a bunch to know for sure.

**Comment by NeroOneTrueKing** [comment]
I tried reproducing it but my drum of earthquake angered the Elder Priest in the first place. I think you're right?

**Comment by NeroOneTrueKing** [comment]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/ba92e4d943a9daaaf70ea8bc45629500c73c8248/src/music.c#L1522

Nope, the Sanctum altar cannot be broken by an earthquake.
