### ISSUE TITLE
Taming a monster in an essence trap and displacing it allows for it to escape alive

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1955]
This also doesn't trigger an alarm and anger the autons against you permanently. I assume this isn't by design because other ways of trying to get them out kill the monster and say the trap was the only thing keeping it alive.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fix: b4ac397d3c81dc1dd68930ce26a04f7a85cc026d
