### ISSUE TITLE
Should be possible to prevent autopickup in shops

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1964]
Regex doesn't work right now, because the things you would want to use (unpaid, zorkmids) aren't part of the string that the autopickup regex parser sees.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Note: Labeled "bug" because I'd expect "zorkmids" at least to be part of the name, since it's included when it's on the floor.

**Comment by amateurhourrrr** [comment]
Do you want this to behave like vanilla does? i.e. never autopickup in shops

Porting vanilla's code for this wouldn't take very long
