### ISSUE TITLE
Do monsters check m_online() before zapping a wand?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#1968]
Demo had a case where a monster zapped through him to hit a target. Code inspection suggests that the muse code relies on mfind_target() to find a safe zap target, but mfind_target() is a general function that will return a monster that's a valid target for ANY of the aggressors attacks. So a monster with multiple ranged attacks can be given a target that's safe for _some but not all_ of its attacks. At least some (example: breath attacks) ranged attacks check m_online() with appropriate flags before blasting, but it doesn't look like muse does.

"The ancient naga zaps a wand of magic missile!  The magic missile hits you.  The missiles bounce off!  The magic missile hits the Green-elf." he targeted straight through me

~The pet *might* have been confused, so it's not certain that this targeting bug exists.~

**Comment by Chris-plus-alphanumericgibberish** [comment]
Demo pulled it from the tty recording: 
![image](https://user-images.githubusercontent.com/3014096/176212957-ffdf3777-f08e-4e2e-9b54-e329ec7630fd.png)

Looks like mfind_target() picked a polearm-ranged target (for which the PC's location isn't relevant) but then mused a wand of magic missile instead, zapping through the PC. 

Should be as easy as adding a m_online() check to an appropriate place in the muse code.

**Comment by demogorgon22** [comment]
Watching the ttyrec, i did check my pet right after it "Status of the ancient naga (lawful):  Level 22  HP 170(170)  AC -20  DR 5, tame, fast." and he was not confused
