### ISSUE TITLE
New polearm code + new turn code can lead to cc being uninitialized in crook targeting causing a crash

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1993]
![image](https://user-images.githubusercontent.com/8377693/181562076-eba9ab94-6e48-45a0-bc56-fb1343ef61a5.png)

Enable classic polearms targeting->apply to select a spot with bent staff-> hit esc -> crashes because MOVE_CANCELLED is not 0 and it is only checking if it is 0 so it uses the uninitialized cc to try to pick up an object

This represents a generally larger problem. How many more instances are there of code checking results of things not being 0 that may be some goofy new movement type constant?

**Comment by NeroOneTrueKing** [comment]
In response to your question, hopefully not that many!

**Comment by amateurhourrrr** [comment]
unfortunately this doesn't seem to be fixed - fuzzing comes across it fairly often still with latest devel

asan report: https://0x0.st/oeU1.log

**Comment by NeroOneTrueKing** [comment]
Is this still an issue?

**Comment by amateurhourrrr** [comment]
I think the first pass fix was 08b172e1b which didn't fully solve it

then I think it was corrected in 434e5cf18 a day later

**Comment by demogorgon22** [comment]
This was fixed aw while ago and is good now.
