### ISSUE TITLE
"You fly down along the stairs." when ascending to the windowless tower

### ISSUE THREAD

**Issue by NetSysFire** [Chris-plus-alphanumericgibberish/dNAO#2008]
Steps to reproduce:

1. Be a vampire.
2. Go into the gnomish mines and explore until you reach the stairs up to the windowless tower.
3. Go up.
4. "You fly down along the stairs."

Expected behavior:

A message that tells you that you go up instead of down.

Version:

The one on hardfought.

**Comment by NeroOneTrueKing** [comment]
Not reproducing this on devel. I get the correct message on first entering the level ("You are standing on the surface, albeit at the bottom of a shear ravine." etc), and no message on further trips up the stairs. Descending the stairs to leave Vlad's tower's area correctly gives the message "You fly down the stairs", as it is a downstairs to leave.

**Comment by NetSysFire** [comment]
Might be fixed in devel since this is the version on hardfought

**Comment by demogorgon22** [comment]
I am unable to reproduce this in dnh either. I believe this is an ndnh bug, not a dnh bug.

**Comment by NetSysFire** [comment]
Closing then
