### ISSUE TITLE
Water flowers do not cause silver damage when kicking with them

### ISSUE THREAD

**Issue by NetSysFire** [Chris-plus-alphanumericgibberish/dNAO#2019]
Steps to reproduce:

1. Wear the water flowers.
2. Kick a vampire or something else weak to silver.
3. No silver damage.

Confirmed by @demogorgon22 in #hardfought.

Expected behavior:

They do silver damage because they are silvered and their description says that.

**Comment by NeroOneTrueKing** [comment]
ARTA_SILVER was changed to be implemented as a permanent silver-poison and isn't being applied by gloves/boots. Changing it back to being implemented in obj_silver_searing should do the trick.
