### ISSUE TITLE
Elder brain mind blasts deal damage over again and don't check death

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2029]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/9af35332817c0d5ff66f35ba9bc7b9fa4ffc71ff/src/monmove.c#L1902-L1905
Not sure if it is intended for them to be doing double damage or not (it is a lot of damage) but this is after general mind blast damage is done and this does not check if the monster has died and set it appropriately for cleanup.

**Comment by amateurhourrrr** [comment]
Is this fixed in devel now?
