### ISSUE TITLE
Artifacts with fixed MT_WEIGHT do not scale weight with player applied material changes

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2038]
It would be really nice if they did, it feels like platinum dragon plate (heavy) should have a positive interaction with the silver flame cult (make it less heavy by making it mithril), as well as likely other artifacts that I have yet to interact with and want to smelt away the immobility of.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fix: 23ea03e876bb6f51b3118dfdbaaa8b93180f0278
