### ISSUE TITLE
Pseudonatural templated enemies should be highlighted

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2039]
As it stands, they can randomly generate and look no different than regular monsters while being among the most dangerous monsters. They should be highlighted some color like zombies are so they stand out right away and the player can know "oh that's a brain eater that can kill me through my life saving" and not just think it is another normal monster. As it stands, it is very antiqol needing to manually check each monster from a range to make sure it doesn't have that very deadly template.

**Comment by NeroOneTrueKing** [comment]
Expansion: to be able to specify a highlight color OR a monster color override for any template.

**Comment by NeroOneTrueKing** [comment]
Actually looking at the display code, yikes.

Data goes from
Monster/object/dungeonfeature/etc -> encoded into a unique glyph -> decoded into a symbol and forecolor and backcolor.

Zombies are their own set of glyphs. We can't generalize, we'd need to add a set of glyphs for every template we want to support.
