### ISSUE TITLE
Xorns can eat magic chests

### ISSUE THREAD

**Issue by NetSysFire** [Chris-plus-alphanumericgibberish/dNAO#2061]
I placed a magic chest on the rogue level, next to the downstairs. I also stored my alignment keys on the square with the magic chest.
When I came back the chest was gone - and a Xorn nearby. The alignment keys were still there. Yes, the magic chest was bolted down.

This happened in ndnh, but Demo said it is likely upstream. He also said that this was fixed in the past, so this may either be a regression or a new edge case.

**Comment by lapis413** [comment]
I believe i also had a Xorn eat the magic chest in soko, in a game where I put it off for a while, but I wasn't able to tell exactly what did it

**Comment by NeroOneTrueKing** [comment]
I can confirm, Xorn will eat magic chests (both locked and unlocked).

**Comment by NeroOneTrueKing** [comment]
With all the extra handling these chests need, maybe it would be better for them to turn into dungeon features when opened (and only allow opening them on standard room tiles).

**Comment by Chris-plus-alphanumericgibberish** [comment]
Is this a bug? This sounds like the expected behavior to me?

**Comment by NetSysFire** [comment]
Magic chests are incredibly rare and valuable and should not be eaten by a random Xorn.

**Comment by k21971** [comment]
IMO something like this should be off-limits as something edible. I could see a gelcube swallowing it and making off with it, but not actually digesting it.
