### ISSUE TITLE
Earth plane ceiling collapsing doesn't reblock previously dug out squares

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2065]
This allows monsters to gaze attack you through the stone, you to see through the stone as if it isn't there, and for monsters to hit you with reach attacks through the stone.

**Comment by NeroOneTrueKing** [comment]
reproduced:
![image](https://user-images.githubusercontent.com/28197216/197405763-d7a6e1aa-8398-4904-a040-0a1b1679c56f.png)
weird, and the commit history places it all as dnao
