### ISSUE TITLE
Charging a preservative engine with blessed charging sets its charge to 0

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2076]
This seems like it isn't implemented in the read.c? recharging code probably?

**Comment by NeroOneTrueKing** [comment]
Looks like this is intentional behaviour!

[src/read.c:1416-1490](https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/85b164eabc360e6e60c157ecab4a6528f64b85a6/src/read.c#L1390-L1417)

Since they're demonic tools, cursed charging works on them best.
