### ISSUE TITLE
Dipping poisoned weapons into healing doesn't work for all weapons

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2081]
Shopkeeper services can poison more weapons than normal potions can. You can poison a weapon with a shk and then dip it into healing to unpoison it but it won't work because it isn't normally poisonable by potions.

**Comment by NeroOneTrueKing** [comment]
I'd say the bug is that shopkeepers can poison weapons that shouldn't be poisonable.

**Comment by demogorgon22** [comment]
I liked to think of it as a feature.
