### ISSUE TITLE
Incantifiers can eat fake amulets of yendor

### ISSUE THREAD

**Issue by NetSysFire** [Chris-plus-alphanumericgibberish/dNAO#2108]
Steps to reproduce:

1. Be an Incantifier.
2. Go into the rogue level or simply wish up a cheap plastic imitation of the amulet of yendor.
3. Eat it. In this case, the amulet was not identified.
4. You gain energy.

Expected behavior:

Incantifiers can not eat this non-magical amulet.
This was found on notdnethack but this is an upstream bug.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed: a97b522830414528ecc4583a9fdce3f3adff3b6f
