### ISSUE TITLE
Punishment spell can crash if player is non corporeal

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2128]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/ca3c01a278c3991a9e83d6ad18c8b8644498c68a/src/mcastu.c#L6102-L6103
The code assumes that punish() sets uball. Malphas seems to block this. This is also not the case for amorphous , whirly, and unsolid forms where a ball is just dropped. This leads to a null ptr deref crash in these cases.

**Comment by demogorgon22** [comment]
The incarcerate spell has the same bug
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/ca3c01a278c3991a9e83d6ad18c8b8644498c68a/src/mcastu.c#L6180-L6181

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by 6cf373c
