### ISSUE TITLE
Artifacts can be destroyed by polymorph and hungry monsters

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2146]
I believe players cant destroy them by munching anymore.

https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/e0a6e1e59a95f9f934478b73b5d7996334efe26b/src/mon.c#L2409
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/e0a6e1e59a95f9f934478b73b5d7996334efe26b/src/mon.c#L2068

Somewhere polyobj or something checks with a 95 resist chance for artis instead of 100 on polying, and I'm pretty sure that is meant to be 100 with the way that artis are now.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by 5116074cb59070371392fd8b46baf626edfcf9eb
