### ISSUE TITLE
Is there a way to guarantee access to yog-sothoth for binders

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#2240]
Any other roles can invoke the silver key on the alter but binders have to count on their luck to get a yog portal

**Comment by RikerW** [comment]
hyperborean dials can be used by anybody without sleep res, so binders can always use those, i believe. i don't think any are guaranteed for binders (madmen get one, for example) but if it's an issue, one could probably be thrown somewhere random in binder quest or something

**Comment by baoliejuan** [comment]
So you can wish for one, I somehow thought it was unwishable
