### ISSUE TITLE
Some weird behavior in convict quest

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#2242]
1.The Iron Ball of Levitation don't grant increased carrying capacity equal to its current weight, instead it has negative weight, which adds twice it's weight to actual carrying capacity
2.Inherited artifact have the item type of scrap, making it unusable outside it's invoke effect. Maybe this is intended since it could also make sense.

**Comment by RikerW** [comment]
The first one is intended, I believe- the idea is that it has no weight AND buffs your carrycap? It shouldn't actually be adding twice its weight, just increasing your carrycap by that much and not costing any.

The second is not intended and I'll fix that. It's set as a scrap in the des file, but when inherited it should not be scrap anymore.

**Comment by baoliejuan** [comment]
I think the intension is to make it carry it's own weight, but now you can read punishment to reach it's max weight and get extra 1640 carrying capacity (silver flame's share burden only increases by 200 and currently not working, for comparison), which is more than some spice's max carrying capacity, plus it will show you are carrying negative weight which is something weird

**Comment by Chris-plus-alphanumericgibberish** [comment]
It's working as intended. Regarding the discrepancy between the ball and the silver flame effect, things that just one role gets can be a lot stronger than things everyone can get.
