### ISSUE TITLE
Random shrieker spawn of a serpent man of Yoth can lead to an impossible in devel

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2246]
This is ndnh devel, but this appears to be a dnh devel bug. (mndx 500 is serpent man of Yoth)
![image](https://github.com/Chris-plus-alphanumericgibberish/dNAO/assets/8377693/5868ed17-24fa-4b11-9334-c8e5da4eab41)
uncommon() seems to care about the insight gate. Not sure how this interacts with other of the new insight gated monsters that have been added that may be a target for randmonst()? no clue.

**Comment by demogorgon22** [comment]
Confirmed that this can also happen for lucksuckers

**Comment by Chris-plus-alphanumericgibberish** [comment]
The list of valid monsters is persistent unless reset_rndmonst is used. Call it when changing insight: ed9cb4380a07174d9ef62544406cdd94f6924984
