### ISSUE TITLE
yochlol_initinv called with an extra argument

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2254]
Called as
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/b1cf0152c7aa9492007074aa3883b5de40bf9f99/src/makemon.c#L14508
But defined as:
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/b1cf0152c7aa9492007074aa3883b5de40bf9f99/src/makemon.c#L433-L434

**Comment by Chris-plus-alphanumericgibberish** [comment]
Bad merge, basically
