### ISSUE TITLE
Non artifact GSSDW weapons crash on hit in devel with certain insight and sanity values

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2259]
![image](https://github.com/Chris-plus-alphanumericgibberish/dNAO/assets/8377693/c2111b07-12ee-452f-8868-ffb45b85a150)
Found fuzzing ndnh, but this is a bug in dnh code. 
How to replicate - create a wizard, set insight to 20, wish for a flowing quarterstaff, and hit a lichen with it
The cause here should be clear if the relevant code is read. It appears that the mercurial skies artifacts assume oart is guaranteed to exist in some spot that it may not.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by dropping the artifact requirement
