### ISSUE TITLE
Saving while engulfed and punished can lose ball or chain

### ISSUE THREAD

**Issue by AmyBSOD** [Chris-plus-alphanumericgibberish/dNAO#226]
**Describe the bug**
If the player is both engulfed and punished, saving the game may result in losing the ball and chain, and sometimes the game may produce a disorder message or crash.

**To Reproduce**
1. Wish for a nonblessed scroll of punishment and read it
1.5 (Optional) Pick up the heavy iron ball
2. Generate an energy vortex or other engulfer and wait until it engulfs you
3. Save the game while engulfed
4. Load the game; you might get an error message immediately, but not always, and getting out of the engulfer will most probably reveal that the ball and/or chain have gone missing and you're no longer punished even though you should be

**Expected behavior**
The player should still be punished after saving and loading the game, and the ball and chain should reappear once you're out of the engulfer.

**Desktop (please complete the following information):**
 - OS: probably any, but seen on both Windows (XP and 7) and Unix

**Additional context**
The exact behavior of the crash varies depending on whether you picked up the ball or not, and there may also be other factors. A fix is here: https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/5edaa33c

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by porting the SLEX fix and vanilla's sanity checking
