### ISSUE TITLE
Error in unmaintained function "extcmd_via_menu"

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#245]
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7239801 in __GI_abort () at abort.c:79
#2  0x0000555555727138 in panic (str=0x555555d036f8 "No window slots!") at src/end.c:518
#3  0x0000555555c5f0c2 in tty_create_nhwindow (type=4) at win/tty/wintty.c:936
#4  0x00005555556296d5 in extcmd_via_menu () at src/cmd.c:421
#5  0x0000555555c5a2a2 in tty_get_ext_cmd () at win/tty/getline.c:260
#6  0x0000555555629291 in doextcmd () at src/cmd.c:325
#7  0x0000555555652ebf in rhack (cmd=0x555555fc42a0 <in_line> "#") at src/cmd.c:5446
#8  0x00005555555b2ad7 in moveloop () at src/allmain.c:2205
#9  0x0000555555c5881f in main (argc=4, argv=0x7fffffffe3e8) at sys/unix/unixmain.c:296

**Comment by NeroOneTrueKing** [comment]
Fixed by fixing the docarve menu bug that was using up window slots. Once the maximum number was opened and left orphaned, the next thing that made a menu would crash with this error.
