### ISSUE TITLE
Certain new covetous warping cannot handle levels with certain conditions.

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#248]
#0  0x0000555555684c35 in newsym (x=80, y=-38) at src/display.c:771
#1  0x0000555555b48493 in rloc_to (mtmp=0x555556047470, x=80, y=-38) at src/teleport.c:1270
#2  0x0000555555940e9b in mofflin (mtmp=0x555556047470) at src/mon.c:5353
#3  0x0000555555c115e2 in tactics (mtmp=0x555556047470) at src/wizard.c:381
#4  0x000055555595cae0 in dochug (mtmp=0x555556047470) at src/monmove.c:1132
#5  0x00005555559508f1 in dochugw (mtmp=0x555556047470) at src/monmove.c:98
#6  0x000055555591b6cd in movemon () at src/mon.c:2082
#7  0x000055555559f598 in moveloop () at src/allmain.c:824
#8  0x0000555555c58851 in main (argc=4, argv=0x7fffffffe3e8) at sys/unix/unixmain.c:296

Arch and master liches are confirmed to exhibit this behavior.
Before this crash in mofflin calls eofflin which filled a coord struct with 80 -31. Because the way eofflin handles a certain condition returns goods[0] which when the level is in this condition, goods[0] is uninitialized so garbage x and y are set to be used at the position the covetous monster warps to.
Also the above functions have names that are unreadable and aren't very clear what they are supposed to do based on the name.
I'm not sure what the level conditions are that cause goods to be empty. One of them happened with 1404 monsters, one happened with 735 so it does not require a full level, probably just a full area around the player?

**Comment by NeroOneTrueKing** [comment]
Fixed by b333e91 in compat-3.21.0.
