### ISSUE TITLE
Making a hungry dead can crash if it cannot create a blob of preserved organs

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#249]
#0  0x000055555579a8fb in m_initinv (mtmp=0x5555562e4560) at src/makemon.c:5990
#1  0x00005555557a2fb4 in makemon (ptr=0x555555f6fd70 <mons+54768>, x=37, y=18, mmflags=0) at src/makemon.c:7916
#2  0x000055555578781c in m_initgrp (mtmp=0x5555562e4120, x=42, y=7, n=0) at src/makemon.c:158
#3  0x00005555557a2f0b in makemon (ptr=0x555555f6fd70 <mons+54768>, x=42, y=7, mmflags=0) at src/makemon.c:7905
#4  0x00005555555aac7b in moveloop () at src/allmain.c:1374
#5  0x0000555555c58851 in main (argc=4, argv=0x7fffffffe3e8) at sys/unix/unixmain.c:296
```
 } else if(ptr == &mons[PM_HUNGRY_DEAD]){
    struct monst *blbtmp;
    blbtmp = makemon(&mons[PM_BLOB_OF_PRESERVED_ORGANS], mtmp->mx, mtmp->my, MM_ADJACENTOK|MM_NOCOUNTBIRTH);
    blbtmp->mvar1 = (long)mtmp->m_id;
}
```
blbtmp->mvar1 is set before verifying blbtmp isn't null

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by Nero
