### ISSUE TITLE
Kicking off map can lead to crashes (bug 2)

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#256]
#0  0x000055555568b6b7 in back_to_glyph (x=64 '@', y=21 '\025')
    at src/display.c:1752
#1  0x00005555556798b6 in map_background (x=64 '@', y=21 '\025',
    show=1) at src/display.c:225
#2  0x000055555567ce20 in feel_location (x=64 '@', y=21 '\025')
    at src/display.c:616
#3  0x00005555556e9d40 in dokick () at src/dokick.c:1445
#4  0x0000555555652ee1 in rhack (
    cmd=0x555555fc42a0 <in_line> "\004") at src/cmd.c:5447
#5  0x00005555555b2ad7 in moveloop () at src/allmain.c:2205
#6  0x0000555555c58851 in main (argc=4, argv=0x7fffffffe3e8)
    at sys/unix/unixmain.c:296
```
Must be blind and kick down.
I don’t know why but this works on ranger quest home. kick down the bottom. arc quest home which should be identical it doesn't work and instead you thump and get an impossible.
Pirate quest when i do this while standing on water it doesn’t crash and throws the same impossible as the arc quest.It doesn't thump on pirate quest.
feel_location should really make an isok check or something…
https://sourceforge.net/p/nethack/NetHack/ci/e2fffafb7c9e55f6f5bd9f75ab6e982c3cc862e9
https://sourceforge.net/p/nethack/NetHack/ci/9af9cf30c8bc8087a72c4eca2be7a258fca1aa56
should fix the impossible part but the part where it crashes… idk. it should always thump when you kick off the map. when it says “you kick an empty space” that means something is wrong with the level?
```
Above are my mostly unrevised internal notes. Should be easy to replicate.

**Comment by NeroOneTrueKing** [comment]
Fixed by #275
