### ISSUE TITLE
Characters don't start with max pw

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#272]
They'll always start 2-3 power down from their maximum, regardless of race/role? Seems like it processes after the half-dragons-get-15-pw check, since a hlf knight had 15/18 power at T:0.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed on dev

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by a565ab05a5fe4083952de9666dfc919368014941
