### ISSUE TITLE
Chaos3 cracks:2 can have no downstair

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#287]
The lava lake level in the mordor chaos quest (where there's a big lake in the middle, NOT the one with the high shaman of moloch) can have no downstair. Confirmed with a savefile. The stairs will put you on a random spot every time. (for ease of testing - savefile starts you on lvl 11, bugged one is lvl 10).

[0wizard.zip](https://github.com/Chris-plus-alphanumericgibberish/dNAO/files/3938013/0wizard.zip)

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed on dev.  Cause is bad .des

**Comment by Chris-plus-alphanumericgibberish** [comment]
fixed by b446c054603a356c4530e7a10ae9b026105e3e96 (Fix bad staircase positioning on mordor cracks lava lake level)
