### ISSUE TITLE
Unclear interaction between shoot-all launchers and throwables

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#288]
Wielding the BFG (or pen of the void with Eve bound into it), you currently:
Get the launcher's multishoot bonus, and it says you "shoot" the throwable, but the range is its default.
Boomerangs still move in their boomerang arcs when shot.

What is the intended behaviour?

**Comment by Chris-plus-alphanumericgibberish** [comment]
After reflection, assuming that throwable is limited to weapons and the like rather than potions, the intention is to use the launcher's multishoot bonus AND range.

Boomerangs should still move in their arcs, since that is their unique feature, but should also use the multishot bonus.

**Comment by NeroOneTrueKing** [comment]
Currently, potions and generally-not-throwables can be shot by shoots-all launchers.
That's because by definition, anything is valid ammo for them.

Otherwise, current behaviour is as intended then.

**Comment by NeroOneTrueKing** [comment]
I don't think anything needs to change from current behaviour. Closing.
