### ISSUE TITLE
Death-spear is broken af

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#289]
It's probably pretty stupid (bypasses monster MR, player MR, etc.) but it also segfaults when invoked on empty square (doesn't check if there's a monster there).

**Comment by NeroOneTrueKing** [comment]
Segfault thing: seriously needs to be fixed.
Balance-wise: here's a few ideas, not cumulative. 1) Drain a level from wielder when invoked (bypassing MC's 1xp-below-next-level feature). 2) rnz(1000) timeout. 3) Limited charges, refilled by a few (up to a max of 7) when praying on a co-aligned altar (kind of like a water prayer).
