### ISSUE TITLE
Dilapidated Armories are too much of a free loot-haul

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#292]
Potential changes to address the issue:
- Make the brown puddings and rust monsters generated inside give no XP.
- Disable artifact generation for items generated inside.
Edit: more potential changes:
- Limit the max size of armories to 20 (interior) tiles as a special-room-creation requirement

**Comment by Chris-plus-alphanumericgibberish** [comment]
Armories limited to depth 2 and below on dev, and restricted to 9-25 squares in size.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by bcf0a709b0e5889d5b0116392ffc78057a3e553a
