### ISSUE TITLE
Downstairs not generating on Chaos Quest, Cracks 2

### ISSUE THREAD

**Issue by Wikid-VoR** [Chris-plus-alphanumericgibberish/dNAO#298]
I had to levelport down. I hope this is the right place for a bug report these days.  dNethack is as enjoyable as ever.  Thank you for the work!

**Comment by RikerW** [comment]
Are you running the latest version? That should be fixed by now. See #287.

**Comment by Wikid-VoR** [comment]
Thanks.  I'm playing on the public dNAO server as VoR.  Perhaps I started the current game just before the fix.  Anyhow, it was good fun to discover a workaround via levelport!
