### ISSUE TITLE
Monster life saving messages

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#305]
All messages use cansee() instead of canseemon(), because the Amulet code assumed that you were looking at a glowing object in the monsters square instead of the monster itself.

Problems:
- I think cansee() respects illumination, meaning that you can't see glowing amulets in dark squares!
- Not all effects glow/are separate from the monster's appearance.

**Comment by NeroOneTrueKing** [comment]
LIST IS:
- anachrononaut quest
  - can see monster
- uvuuduam + prayerful thing
  - can see glowy thing on monster's head square
- lifesaving items
  - can see glowy thing on monster's head square
- alabaster decay
  - can see monster
- fractured kamerel
  - can see monster?
  - they crack and scream
- illuminated
  - can see glowy thing on monster's head square
- polypoids
  - can see their mask crack?
- kamerel becoming fractured
  - same as fractured kamerel?
