### ISSUE TITLE
Tomb-Herds can probably mess up statue corpses

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#306]
Herds should really just pick up their statue in a protected object chain and drop it again when they die.

**Comment by NeroOneTrueKing** [comment]
Alternatively, if the statue has an attached monster, the tomb herd is based off of that (overriding any existing faction).
Optional: when slain, the tomb herd is saved to the oattached of the statue it drops (minus the tomb herd faction).

**Comment by NeroOneTrueKing** [comment]
Tomb herds actually currently cannot animate statue corpses.
`if(obj->otyp == STATUE && obj->oattached != OATTACHED_MONST && !(obj->spe) && u.uinsight > rn2(INSIGHT_RATE*70))`
And from the looks of things, if they could, they would inherit the statue corpse properly. Closing -- hopefully I won't have to eat these words later :)
