### ISSUE TITLE
Misc Fossil Issues

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#321]
Casting Stone to Flesh on a fossil yields a corpse even for no-corpse monsters.
Zapping Undead Turning on a fossil yields a skeleton of the monster, even if monster has no bones.
Both methods are able to create real copies of unique / no-wish monsters, albeit without their inventory.

**Comment by Chris-plus-alphanumericgibberish** [comment]
I've applied the figurine-wishing rules to fossils in dev, but have not addressed the other two problems.

**Comment by NeroOneTrueKing** [comment]
The figurine-wishing rules should be applied to statues as well, for consistency.

Maybe casting/zapping Undead Turning on a fossil of a unique could create a skeletal doppelganger?
