### ISSUE TITLE
White dragon scales don't remove swimming from monsters when removed

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#334]
I think it also leaves the magical breathing behind as well but I'm not sure. Not sure if this happens to other armor based monster extrinsics as well.

**Comment by NeroOneTrueKing** [comment]
I am having difficulty reproducing this issue at all.
Can you consistently cause it?

**Comment by NeroOneTrueKing** [comment]
I can't reproduce this bug; whatever was causing it may have been fixed since this was reported. Closing until it gets reproduced.
