### ISSUE TITLE
Pets still like to drop important items on the VoTD

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#335]
Their AI still will switch to dumb AI and start collecting various junk items, which they will then drop all of when they enter a different level.

**Comment by NeroOneTrueKing** [comment]
This stems from all monsters being treated as mindless while on the valley of the dead:
`#define mindless(ptr)		(((ptr)->mflagst & MT_MINDLESS) != 0L || on_level(&valley_level, &u.uz))`
It's a flavour-feature that I'd be happy to axe for the sake of not making bugs like this one. The other option is a lot of special casing, and potential kludging, to make things *appear* mindless in some aspects while on the VotD.

Chris, what do you think?

**Comment by demogorgon22** [comment]
If this behavior is axed, Dantalion mind travel needs to be blocked on the votd, if it isn't already, so the artifact doors can't be warped past.

**Comment by Chris-plus-alphanumericgibberish** [comment]
This got fixed. A key function involved is used both for dropping items as pets and dropping items when killed, and I hadn't noticed.  This led to a variety of nasty bugs. However, this *should* all be straightened out now.
