### ISSUE TITLE
Prismatic Spray can lead to printing weird strings

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#339]
Monster spell prismatic spray, when it kills a monster, will print that the monster is caught in the %s but the thing in the %s tends to be inventory items or other previously recently seen strings.

**Comment by NeroOneTrueKing** [comment]
Incorrect strings are a minor problem, but man if that doesn't throw warning signs that things are going funky somewhere

**Comment by NeroOneTrueKing** [comment]
Can you confirm that this is still an issue on latest (Jan 9 2020) devel-3.19.0?

**Comment by NeroOneTrueKing** [comment]
Found and fixed a bug that I could reproduce this issue using, and it appears to be the only way to get `killer` to point to the obuf array, so hopefully this issue is solved!
