### ISSUE TITLE
Zombies on binder quests have a redundant name

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#355]
Binder quest zombies are called "zombie zombies." This should probably just be cut down to "zombie" of the mfaction is zombie and the permonst is zombie.

**Comment by NeroOneTrueKing** [comment]
Code-diving:
Turns out that this is caused by the player's race, `urace.zombienum`, which is part of the race array. Everybody's zombie form is `PM_ZOMBIE` (except for clockworks), which is why zombies are the base creatures being generated.

Makemon is spaghetti >_>

**Comment by NeroOneTrueKing** [comment]
Hmm, changing everyone's urace.zombienum to be what you'd expect (ie dwarfs have `PM_DWARF`, not `PM_ZOMBIE`) seems to work. And `zombienum` appears to be _exclusively_ used for creating graveyards full of the player's race in the binder quest.
