### ISSUE TITLE
Uranium imp passive can trigger even if it's dead.

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#370]
riker:
@ChrisANG earlier today got "You hit the uranium imp! The uranium imp warps reality! placing defunct monster onto map? program in disorder"

Was this fixed by the adjustments to passive attacks earlier?

**Comment by NeroOneTrueKing** [comment]
Nope not fixed needs fixing :(
