### ISSUE TITLE
Energy to 0 and Incantifier oddities

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#404]
The "set energy to 0" seduction is quite nasty for Incantifiers.  Also, if the Incant is already fainting it *gives* them energy.

Possibly the balance is fine.  Incatifiers are quite powerful, and a vulnerability that follows naturally from the normal rules of the game is not a problem.

Either way, the gain energy part should be fixed.

**Comment by NeroOneTrueKing** [comment]
In my opinion, draining `(u.uen*99 + 99)/100` would be fairer, giving the player a handful of turns before they're victim to potentially fainting (and the helplessness associate with that). Or some other nearly-1 fraction.
