### ISSUE TITLE
Add light source sanity checking

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#415]
The light source code keeps generating save-eating-bugs due to bad pointers.  A sanity check should be implemented to detect and remove bad lightsources before they cause crashes.

Example: lightsources that claim to have an object pointer attached, but for which the matching object can't be located (based on the pointer) should be deleted with a warning message.

**Comment by NeroOneTrueKing** [comment]
Related: the timer-setting code should refuse to set an identical timer, and/or the timer-clearing code should clear ALL of that kind of timer (from the pointed-to object)

(The most recent bug I saw&fixed with lightsources would have been avoided if either of those were the case)

**Comment by NeroOneTrueKing** [comment]
Edit: actually, timers do this properly. It's **lightsources** that still don't. Making a fix.
