### ISSUE TITLE
Allow stolen items to be merged if not `sknown` ?

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#420]
You didn't steal them (if you did, sknown would be set), and you haven't magically IDed them yet to know either.
They'll just get jumbled in with your other <foo>. It wouldn't be too much of a stretch to say shopkeepers would lose track of whether those items were stolen or not too.

**Comment by Chris-plus-alphanumericgibberish** [comment]
stolen is meant to preserve information about what the shopkeeper does and doesn't own, to make them more resistant to credit cloning; allowing this would make it completely nonfunctional (of course, at the moment it's **almost completely** nonfunctional anyway).  Andromalius also needs it to make his taboo have even a few teeth.

Instead I would make it so intelligent monsters at least (pets or not) are more reluctant to loot things out of shops.  The pet dog etc. should probably continue to steal things out of shops, basically for old times sake.

Shopkeepers ability to recognize things owned by other shopkeepers is certainly supernatural in nature.
