### ISSUE TITLE
Saving with traps in a certain state crashes during save

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#428]
#0  0x000000000089ecf8 in getlev (fd=8, pid=18324, lev=6, ghostly=0 '\000') at src/restore.c:890
#1  0x00000000008a7d93 in dosave0 () at src/save.c:277
#2  0x00000000008a79e1 in dosave () at src/save.c:83
#3  0x00000000004d0f24 in rhack (cmd=0xe98a00 <in_line> "S") at src/cmd.c:5975
#4  0x000000000041d3e8 in moveloop () at src/allmain.c:2312
#5  0x0000000000b1c8b2 in process_options (argc=0, argv=0x0) at sys/unix/unixmain.c:314
#6  0x00007ffff721ab97 in __libc_start_main (main=0xb1c397 <main+35>, argc=3, argv=0x7fffffffe3d8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3c8)
    at ../csu/libc-start.c:310
#7  0x000000000040364a in _start ()

Happened when saving the game on the earth lich chaos1 level. I think it was a rock trap.

**Comment by NeroOneTrueKing** [comment]
Unless this re-occurs in the updated version, I'm going to call this fixed-in-dev.
