### ISSUE TITLE
Were the conflicts resolved correctly on pull request #421

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#434]
Can't find the correct commit number :/ The conflict was in trap.c.

It was resolved so that "if (!(otmp = trap->launch_ammo)) {" was left as in the current head, and everything else was as in the pull request.

**Comment by NeroOneTrueKing** [comment]
If it was just the fire trap that was causing a merge conflict, than yes I can confirm it was resolved correctly
