### ISSUE TITLE
u.ustuck not always reset when grabber moves away

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#455]
I can produce this with Mammon. He'll grab me, and then use his covetous teleportation to leave. I'm still stuck to him (`"You are held by it"`).

**Comment by Chris-plus-alphanumericgibberish** [comment]
Adding the major bug label because it causes a panic on game load.  I'm removing the panic from the restore code now, but there may be more subtle issues :(

**Comment by Chris-plus-alphanumericgibberish** [comment]
See for reference https://github.com/demogorgon22/notdnethack/commit/5b9e6af8b0b1aa7843ecda3920cc1d4268c0644d
