### ISSUE TITLE
Lifesaving/Digestion-attack interaction

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#474]
Digestion attacks used to simply use up an amulet outside the normal monster-death-handling function, resulting in no message about the amulet glowing and in the amulet not being type-IDed for the player.

This was presumably because the monster is inside the digester's stomach when the amulet triggers, so the PC can't see the glow.

The current code passes through the normal function, but doesn't have the key info that the lifesaving effect should not be visible.

**Comment by NeroOneTrueKing** [comment]
My gut feeling is that this is an instance where a global-scope variable is appropriate. The other options are to either give `mondead()` (and `lifesaved_monster()`) another parameter, or kludge something to hide the monster from view. Thoughts?

**Comment by NeroOneTrueKing** [comment]
This works, and is an example of a "kludge to hide the monster from view":
```
char cantseethis = (viz_array[y(mdef)][x(mdef)] & (IN_SIGHT | COULD_SEE));
viz_array[y(mdef)][x(mdef)] &= ~(IN_SIGHT|COULD_SEE);
xkilled(mdef, 2);
viz_array[y(mdef)][x(mdef)] |= cantseethis;
```
