### ISSUE TITLE
Weeping Angel Contamination Doesn't Interrupt Travel

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#496]
When receiving the message about the image in your mind, travel should be interrupted instead of continuing to run towards them and continuing to get more and more contaminated. It probably shouldn't interrupt if you reflect it. This should probably actually apply to all multiturn actions, not just travelling.

**Comment by NeroOneTrueKing** [comment]
It does call `stop_occupation()` -- I think the root bug here is that `stop_occupation()` doesn't interrupt travelling.
