### ISSUE TITLE
Tame polypoid beings can turn into tame shopkeepers.

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#511]
What horrid bugs does this unleash?

**Comment by NeroOneTrueKing** [comment]
It looks safe. Shopkeeper-related things don't check PM_SHOPKEEPER (which is why we can have shopkeepers that aren't human).
Shopkeeper-related things check `mtmp->isshk`.

**Comment by Chris-plus-alphanumericgibberish** [comment]
I just barred polypoid beings from turning into shopkeepers, but maybe I didn't need to do that.

(By baring them from turning into anything with an extra struct specified in monst.c)
