### ISSUE TITLE
Spellcasting artifacts overcome all spell failure

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#516]
The special spellcasting artifacts (Stormhelm, annulus, etc) just immediately return 100%, thus bypassing all special sources of spell failure, including the effects of the spire.

**Comment by NeroOneTrueKing** [comment]
Would improving splcaster by -1000 (like some roles' special spells) be acceptable?
