### ISSUE TITLE
Genociding "master mindflayer" as a monk genocides you

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#519]
C343-395
https://github.com/NetHack/NetHack/commit/fe5d79c85943314831f6a0a931aece8401462194

**Comment by Chris-plus-alphanumericgibberish** [comment]
Technically not a bug.

However, self-genocide-by-role-tile should be removed.

And genocides should probably only go through if the whole string matches the target, instead of only partially matching.

**Comment by NeroOneTrueKing** [comment]
It would probably solve a number of wishing issues to stop matching role-titles as monster types, but I wonder what bugs that might cause
