### ISSUE TITLE
Drinking a wielded polymorph potion can crash

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#520]
C343-398
If you turn into a form not allowed to wield weapons it drops the weapon before calling useup() and this is bad and crashes.
https://github.com/NetHack/NetHack/commit/1ad1e07d7a1ffa38ea0eccf046ea0ec3ed3c9b40

**Comment by Chris-plus-alphanumericgibberish** [comment]
Adopted the devteam's fix
