### ISSUE TITLE
Panic cause by stoning engulfer while punished

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#521]
C343-59
Very messy. Attempted to replicate by punishing myself, being engulfed by a purple worm, and then turning into a cockatrice. It proceeded to eat me alive, then I was expelled. It did not die as soon as it had a cockatrice inside of it. It then tried to bite me and died to stoning, then I tried to move and the game crashed.
https://github.com/NetHack/NetHack/commit/e723710c82a5b42bea1f398cc1397c7c38819eb9

**Comment by Chris-plus-alphanumericgibberish** [comment]
Added the major bug tag on the grounds that, since panics and punishment have both been known to shred saves, the combination is very scary.
