### ISSUE TITLE
Stoning monsters can fail to anger them

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#522]
Stoning peaceful monsters on your first hit, so they are turned into a statue before they can get mad doesn't anger them. 
Should you stone to flesh their statue, they will come back peaceful.
Before the xhity merge, this was not the case.

Edit: for clarity, this was tested using a wielded cockatrice corpse

**Comment by NeroOneTrueKing** [comment]
ooh that's interesting
