### ISSUE TITLE
Energy regen on artifacts is broken

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#523]
They appear to actually be providing regular regeneration when they are supposed to give energy regeneration. Tested this as in incantifier wizard.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Update: It works on human wizards.

My test suggest it doesn't give *anything* to incantifiers.

**Comment by demogorgon22** [comment]
Update, I tried to test it with two items that provide eregen and for some reason I thought Shield of Yggdrasil gave eregen, not regular regen. So it does not appear to accidentally be providing regen, but instead doing nothing for incantifiers.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Incants only apply energy regeneration to spell upkeep, never to actual energy regeneration.
