### ISSUE TITLE
Fractured and gaze attacks

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#524]
Fractured don't have eyes anymore, which is why they skip making gaze attacks.

The better gaze attack handling in xhity can probably deal with this in a more complete way.

**Comment by NeroOneTrueKing** [comment]
Should `haseyes(fractured) ==FALSE`, as well?

**Comment by Chris-plus-alphanumericgibberish** [comment]
Difficult to say.  That macro's called in a lot of places, so changing it might have unexpected effects.

**Comment by NeroOneTrueKing** [comment]
Notable effects include:

- Resistance to many forms of blindness (Related: how does a Witness of the Fracture see, if they have no eyes?)
- Unable to read scrolls
- More easily kicked by the player

Looks fine to me; I'll write up the change
