### ISSUE TITLE
crossbow doesn't enjoy any multi-shot benifits from skill,race or role assets

### ISSUE THREAD

**Issue by jiangjiechu** [Chris-plus-alphanumericgibberish/dNAO#528]
A gnomish ranger can only fire 1 bolt using a normal starting crossbow with a basic crossbow skill level,not 1d3 according to the rule, which makes this race-role combination almost undesirable.
A gnomish ranger with his/her quest artifact Rogue Gear-Spirits is better, but far from 'powerful' as a hero having completed his role quest.
Besides, a crossbow cannot be #twoweapon'ed  with another single handed weapon, even though it is described as a one-haned weapon, which makes the artifact crossbow-sansara mirror combination impossible.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Crossbows gain damage multipliers, not extra bolts. Sansara Mirror is one of the weapons that uses the swap weapon ("belt?") slot, it does not need to be wielded to boost multishot (not sure if multishot affects crossbows, though).

**Comment by jiangjiechu** [comment]
Thank you, but what do you mean by 'damage multiplier'? As I know it is not clearly described in the nethack wiki how a crossbow gets 'damage multiplier' benifits from its skill level or race-role combination.

**Comment by RikerW** [comment]
[See here](https://nethackwiki.com/wiki/User:Chris/dNetHack/Rule_Changes#Tweaked_skills). See the gnome section for the race benefits.

**Comment by jiangjiechu** [comment]
Thanks again!
