### ISSUE TITLE
Lightsaber/potion interaction

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#530]
Lightsabers can be dipped in potions.  Well, maybe you're dipping the unlit side.  But then, double-sabers exist and can still be dipped while double-lit.

Probably *something* should happen.

**Comment by NeroOneTrueKing** [comment]
Idea: if the lightsaber is lit, the potion violently boils and explodes (if it isn't polymorph or blessing holy / cursing unholy water). If the lightsaber is unlit, you get the standard "Interesting..."

Lightsabers would not be poisonable.

**Comment by RikerW** [comment]
I think it's reasonable lightsabers aren't poisonable. Blunt weapons aren't normally poisonable (and the hilt of a lightsaber is pretty blunt, for most sabers at least), and lightsabers really don't need a buff.
