### ISSUE TITLE
Do rogues and fleeing monsters

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#564]
Do rogues still get their sneak attack procs for attacking a fleeing monster? I wasn't getting the messages in my test game.

**Comment by NeroOneTrueKing** [comment]
Melee: yes.
`The ogre turns to flee! You strike the ogre from behind!`
Ranged: also yes, though the messages aren't as nice.
`You throw 2 daggers. The 1st dagger hits the ogre! You strike the ogre from behind! The 2nd dagger hits the ogre. You strike the ogre from behind.`

However, the "strike from behind" messages are suppressed if the blow is lethal. This could be easily changed.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Ok, good :)
