### ISSUE TITLE
Goat sacrifice message bug

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#578]
The Goat sacrifice code will claim  that your god is mollified when actually it's the Goat that is being mollified.

Not sure what the correct message is, happy bleating? The Goat is also only *sorta* supposed to resemble an actual goat, so happy bleating is not really a good choice :(

**Comment by NeroOneTrueKing** [comment]
There are many incorrect things with the goat arising from copy-and-paste. Unless `lawful_god_gives_angel()` should be anywhere in `goat_pleased()`? And using `u_gname()` there is incorrect too, isn't it?
