### ISSUE TITLE
Monster fireballs

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#590]
Replacing monster fire rays with player-style fireballs has changed fire resistance to be near-required in order to safely retrieve the cloaks of MR from the law quest (it used to be the case that only reflection was essential). 

This has pretty serious implications when trying to bootstrap up low-resource (RNG-cursed) games.

The desired change was for that to be specifiable in some way, but in terms of Junethack it should just be switched back if necessary.

**Comment by NeroOneTrueKing** [comment]
Replace the spellbook of invisibility in Vlad's tower with a ring of fire resistance? 😄

**Comment by NeroOneTrueKing** [comment]
As of the zap rewrite and `elemspell()` in mcastu.c, monsters don't cast player-style fireballs anymore (though it is possible to say certain monsters' ranged elemental spells should explode).
