### ISSUE TITLE
Does the Tulani Eladrin get substituted for a Gae Eladrin in water

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#592]
Code examination suggests not, and it's a minor bug if so.

**Comment by NeroOneTrueKing** [comment]
I think you'll have to explain more about what *should* be happening. I'm adding the minor bug label.

**Comment by RikerW** [comment]
I believe Tulani Eladrin should be completely replaced with Gae Eladrin in all occurrences where they spawn, des files, statue traps, masks, etc. The code right now just genocides one or the other (preventing spawns) at the start of the game, I think, so nothing spawns instead? or possibly a random monster (but not a specific replacement like it should be)

**Comment by NeroOneTrueKing** [comment]
I am dumb -- I somehow had in my head that this meant that Tulani should polymorph into Gae when stepping into pool/water tiles (and turn back into Tulani when leaving). 😖

**Comment by NeroOneTrueKing** [comment]
Tested -- even if Gae Eladrin (or Dracae Eladrin) appear in Oona's tower, there will be Tulani Eladrin on the plane of water.

**Comment by RikerW** [comment]
Fixed in #1125.

**Comment by NeroOneTrueKing** [comment]
I tested to confirm this is fixed. Great!
