### ISSUE TITLE
Rarely, hell special level generation will fail

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#614]
The game will crash instantly, no time to view the level shown. Possibly linked to genocide overuse (crashing when it tries to place a monster from a species geno'd?), but that's just something I vaguely remember. Had it happen last asc with the first level down from the mystery stairs. 

Geno list at that point: L, b, h, Y, nightgaunts, hunting horrors, woodchucks
Extinctioned: deep ones (not sure if it was at that point yet though), gnomes, monotons

[dumplog, if it helps identify via kills list or something like that, note that ; was geno'd on water so it wasn't that](https://www.hardfought.org/userdata/r/rikersan/dnethack/dumplog/1589993777.dnh.txt)

This has been seen before, but I don't recall if it was identified and/or fixed or not.

**Comment by NeroOneTrueKing** [comment]
Without further evidence that genocide is at fault, I'm going to rule that out as the crash cause. Wiztesting (genociding everything and visiting all hell levels) isn't reproducing a crash. A crashlog would be very helpful -- try to procure one from K2 next time this happens, please!

**Comment by RikerW** [comment]
Confirmed this is still a problem in 3.20. No crashlog found yet.
