### ISSUE TITLE
Mother Hydra and Father Dagon need review

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#636]
They are currently tamable, not unique, not proper-name, and wishable.

Lower-priority, but their "returning" mechanic means that they can (and are almost likely to) appear in the Anachrononaut quest -- is this desirable?

Lowest-priority, perhaps their returning mechanic could be changed to instead a) usurp deepest one generation and b) activate on AD_SOUL being triggered for existing deepest ones.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed the flag issues.  In theory it's fine that they would show up in the Ana quest, but the paradoxes kinda bug me so I'm blocking it :D

I think the returning mechanic is fine in terms of how it works, though I actually changed it to buff the host deepest one up to their original levels.
