### ISSUE TITLE
Kicking the air makes noise

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#644]
While useful for waking the Master Assassin, you should at *least* have to drop an item to kick.

**Comment by NeroOneTrueKing** [comment]
Was a change made to fix this, or was it never actually a bug in the first place and just the result of horrible and hard-to-read code flow? Either way, in dev, kicking the air does *not* wake an adjacent leprechaun, nor summons the Master Assassin.
