### ISSUE TITLE
Pass-through displacement should respect ARTA_SHINING et all

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#651]

**Comment by Chris-plus-alphanumericgibberish** [comment]
Pass-through displacement should actually probably be re-crunched as a variant of the shade rules.

Also, if you don't currently get a "your attack passes harmlessly through the shade" message when failing to harm shades, you should.

**Comment by NeroOneTrueKing** [comment]
You do currently get "Your attack passes harmlessly through the shade." when your attack is useless against a shade.

**Comment by NeroOneTrueKing** [comment]
This got fixed in dev somewhere!
