### ISSUE TITLE
Eating amulets of restful sleep is odd

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#666]
Eating an amulet of restful sleep has effects similar to wearing it -- every 1-100 turns, you fall asleep.

However, the amulet_on() and amulet_off() code overrides this; after eating one amulet, putting on and taking off another amulet of restful sleep will purge your cycle of sleepiness.

**Comment by Chris-plus-alphanumericgibberish** [comment]
My read on this is that it's the intended behavior.  However, it is a bit odd, and if one or more other ways to remove the restful sleep intrinsic were added the "put on and remove a second amulet" method could be removed.

For example, perhaps drinking a potion of gain energy should remove restful sleep.
