### ISSUE TITLE
Medusa lacks MA_HUMAN flag

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#685]
Deep ones and Uruk-hai both have the flag and are less human than she is traditionally portrayed.

**Comment by Chris-plus-alphanumericgibberish** [comment]
In some traditions, Medusa is a cursed human, but in others (the ones where she has sisters) she's a descendant of Gaia (making her basically a nymph? Nymphs are fey in dNethack, though :-/).

Medusa's sisters may show up in dNethack some day.
