### ISSUE TITLE
MVM flesh to stone on unique golems can create stone golems

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#688]
My pet throne archon flesh to stoned Arsenal and he turned into a stone golem, making it impossible for me to kill Arsenal that game. Apparently Arsenal has stoning resistance which makes this even more questionable of a thing to happen...
Additionally, in testing
![image](https://user-images.githubusercontent.com/8377693/83907635-c2b47b00-a733-11ea-9aa7-51f655d64050.png)
The throne archon refuses to cast spells at Arsenal, but arsenal is happy to fire his cannonade and magic missile zap at the throne archon. 
There's a lot of bugs here and I have no idea what is going on but it is all very broken.

**Comment by NeroOneTrueKing** [comment]
Bug 1: Turn To Stone checks poly_when_stoned() before stoning resistance. Easy enough to fix
Bug 2: without a ranged weapon, the Throne Archon isn't targeting the Arsenal. Root cause still unknown.
