### ISSUE TITLE
Monsters donning displacement cloaks repeats messages

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#689]
"The forest centaur picks up a piece of cloth.  The forest centaur puts on a piece of cloth.  The forest centaur's outline begins shimmering!"
Additionally, when I killed the forest centaur, the piece of cloth was not type ided as a displacement cloak.

**Comment by NeroOneTrueKing** [comment]
1) There is no repeat message in the string you provided.
2) ID-ing the cloak is possible -- I'll add that.
