### ISSUE TITLE
Monster AI and water needs investigation

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#701]

**Comment by Chris-plus-alphanumericgibberish** [comment]
Will amphibious monsters path through water to reach the player?  They should.

**Comment by NeroOneTrueKing** [comment]
They do not.

We have the following classifications of water-liking:
- eels:  need water
- swimmers: happily path through water
- amphibious: can survive in water if needed
- the rest: never get teleported into water and would drown if they were

By definition of amphibious_mon(), all breathless creatures are amphibious.

**Comment by NeroOneTrueKing** [comment]
If creatures are meant to path through water, they need the MM_SWIM flag.
