### ISSUE TITLE
Maids use the dwarf noble quest guardian text outside of the quest

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#706]
peaceful one on law branch tells me `"Balin is dead, then.  I feared it was so."`

**Comment by NeroOneTrueKing** [comment]
Interesting... just code diving makes it look like this is intended?
@Chris-plus-alphanumericgibberish, please advise

**Comment by Chris-plus-alphanumericgibberish** [comment]
Unintended.  Maids shouldn't even count as quest friendlies for Dwarves.

**Comment by NeroOneTrueKing** [comment]
Would it be fair to say that *all* of the guardian-sounds should be limited to when in the quest?
Other examples include gnomish rangers talking to random gnomes in the gnomish mines or the dungeons.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Unfortunately, I think the correct way to fix this bug is to add a bit to the monster structure, to record whether _this particular monster_ was generated as a quest friendly.

Gnomes in the mines are supposed to be quest friendlies, since the Gnome ranger quest is in the mines.

**Comment by Chris-plus-alphanumericgibberish** [comment]
This apparently got fixed like 3 years ago, but if not it was fixed by guardian factions at the latest
