### ISSUE TITLE
Incantifier starting energy

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dNAO#717]
Incantifier convicts start the game with full energy instead of the 600 specified in u_init.c

**Comment by NeroOneTrueKing** [comment]
Make that, all incantifiers start the game with full energy.
I don't know if this is a bug or not. Chris?

**Comment by Chris-plus-alphanumericgibberish** [comment]
This is a bug.

**Comment by NeroOneTrueKing** [comment]
More clarification, please! 😁 

All incantifiers used to start with about ~1100 power, the usual nutrition amount.
Convict incantifiers started with 600.

Would you like all incantifiers to have non-full pw, or just convicts?

**Comment by Chris-plus-alphanumericgibberish** [comment]
All incantifiers, yeah.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Thinking about it, I bet I broke this when I added code to top-off energy at the start of the game, in order to fix a bug where bonus energy from high wisdom wasn't being taken into account.

**Comment by NeroOneTrueKing** [comment]
Yep, I've taken a look at u_init, and the top-off of health and energy is what causes this issue.
