### ISSUE TITLE
Does Kusanagi unwield if you're wielding it and become ineligible?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#724]
The correct/original Kusanagi behavior was that it could be named and carried after level 22, but only wielded by a level 30.  If you became ineligible while wielding it, you would be blasted and the sword would drop to the floor.

**Comment by NeroOneTrueKing** [comment]
After Riker's change, as far as I'm aware the answer is no -- you will continue to wield it. I hadn't though of that, good catch.

**Comment by RikerW** [comment]
Bleh, it's hard to make ineligable while wielding work. The easiest way is probably check for level draining or amulet stealing? Both of those should pass through the same code regardless of source. I'll make a PR later tonight, if I can.

**Comment by NeroOneTrueKing** [comment]
Losing the amulet of yendor or being drained below XL30 both unwield the Kusanagi no Tsurugi with a nice message.
Changing alignments will not unwield the Kusanagi, which will then blast you every turn until you unwield it.
