### ISSUE TITLE
The Shrouded Dispensary can end up behind the Spire

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#734]

**Comment by NeroOneTrueKing** [comment]
Putting my research down in writing before heading off to bed:

1. The dispensary is a joined level.
2. Joined levels are made by first making a bunch of random "rooms" of `fg` over a blank slate of `bg`
2.1. in this case, it's `room` over `tree`
3. After the map is made (with the random rooms), the .des parts are plopped on top.
3.1. The straight path from the portal to the spire is one.
3.2. The spire itself is another.
3.3. There doesn't appear to be a way to plop a .des section onto the map in a way that doesn't overwrite the entire rectangle
4. When .des parts are aligned to the righthand side of the map, sp_lev purposefully leaves a 2-tile gap between the edge of the level and the mapped region.
4.1. This means that the spire may not completely obliterate rooms that were made on the rightmost edge of the map!
4.2. Similar rules exist for all edges of the map. Can be bypassed best by a (center,center) map.
5. When `init_dungeons()` designates a level of the Neutral quest to contain the branch to the Dispensary, it just says "such and such level shall contain a branch to the Dispensary".
5.1. That is caught in `fixup_special()` in mkmaze.c, and it tries to place the branch in a `0,0,0,0,0,0,0,0,LR_BRANCH,(d_level *)0` lregion.
5.2. `place_lregion()` catches that it's trying to make a branch, and picks a room at random (that doesn't already have a standard starway) to house the branchstairs.
5.3. Even when a room is partly overwritten by the .des sections, any remaining part is valid for holding the branchstairs.

Possible solutions, listed in order of preference:
1. SMOP: Address this comment in `remove_rooms()`: `/* TODO: ensure remaining parts of room are still joined */`
2. Disallow the Dispensary from appearing on the spire level.
3. Overwrite the entire map in the .des (ie no randomized left half).
4. Special case in `mkmap()` to overwrite the rightmost 2 columns with `bg` on the spire level.


Maybe I'll try my hand at 1) in the coming days.

**Comment by NeroOneTrueKing** [comment]
I think I've successfully band-aided the problem as it currently appears for the Spire level.
It would be nice to have the `enhancement (complex)`, but it definitely feels like a SMOP.
