### ISSUE TITLE
Dracae statues are now unlinked from their statue traps in the Tower

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#747]

**Comment by NeroOneTrueKing** [comment]
It's because Dracae Eladrin are flagged as unwishable, and the statue traps are not linked creatures.

**Comment by Chris-plus-alphanumericgibberish** [comment]
The unwishable thing actually made Dracae completely absent from the game, since it affects both statue traps and regular statues/stone-to-flesh.

Therefore, I actually DID fix it in compat.
