### ISSUE TITLE
COA spawn rate is too low

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#762]
how often do you really see him pre-astral

**Comment by Chris-plus-alphanumericgibberish** [comment]
His astral showing is essentially a band-aid covering for the non-implementation of a way to get his attention during the main game.

Currently, this feature is in the underpants gnomes phase of development.

**Comment by Chris-plus-alphanumericgibberish** [comment]
This was addressed by making his arrival insight-dependent.
