### ISSUE TITLE
Rodney will fetch the amulet for you

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#778]
I believe in 3.6+ he is banned from dealing dmg in mvm combat, probably  a good solution here.

**Comment by Chris-plus-alphanumericgibberish** [comment]
The mvm code needs a more robust understanding of who "owns" each item.  Monsters in general shouldn't fight the owner.

Also, at least pre-xhity the elder priest DID deal no damage in mvm combat, which is why the other monsters can best him so easily.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Fixed by c8d06e3c8003462032a06a51081336983fca39a9
