### ISSUE TITLE
Multi-turn wait command does not get interrupted

### ISSUE THREAD

**Issue by AmyBSOD** [Chris-plus-alphanumericgibberish/dNAO#8]
Monsters can come into view and move up to the player, status effects like confusion and stun can time out, and the player may grow hungry or even weak yet the waiting does not get interrupted. It only happens when using "n50." or similar commands, while "n50s" (searching) does get interrupted as it should. The reason for this is that the key rebindings patch makes the wait command (the . command) set no occupation when used as a multi-turn command, and this can be fixed by changing this line in cmd.c:
{"wait", "rest one move while doing nothing", donull, IFBURIED}, 
to:
{"wait", "rest one move while doing nothing", donull, IFBURIED, !AUTOCOMPLETE, "waiting"}, 

This is especially useful if the player is standing in a shop and wants to pass some time without waking up mimics. The player should be interrupted by geckos etc. moving into view, not by being meleed by them (as is currently the case)...

**Comment by Chris-plus-alphanumericgibberish** [comment]
Huh, ok, that is not how you link an issue to a commit... At any rate, commit 09407cf fixes this issue.  Pretty sure there is supposed to be a way to link them directly
