### ISSUE TITLE
Add show inventory weight feature

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#824]
3.6 and many variants have this I believe

**Comment by Chris-plus-alphanumericgibberish** [comment]
I think this would be a straightforward addition. Undeveloped feature is more of a "this can't be implemented without actually hammering out the details" kind of thing.

**Comment by RojjaCebolla** [comment]
- https://github.com/copperwater/xNetHack/commit/cdc3442334a87d89008de21e693a89a0f7c87ee8
- https://github.com/copperwater/xNetHack/commit/29d2cff12fc7b4b11f7a48f044d44d30a254d99c
- (plus assorted bugfixes that came after these commits)
- https://github.com/copperwater/xNetHack/search?o=desc&p=2&q=weight&s=committer-date&type=Commits

**Comment by RikerW** [comment]
done lol
