### ISSUE TITLE
Martial arts offhand on a two-handed weapon isn't very balanced

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#830]
It makes perfect sense, but I think it's a bit weird you can just add some (free, other than skill slots) extra damage if you can unlock martial arts (from an arti gift, monk crowning pantheon, or buer). There should probably be some requirement about expert martial arts skill or only on certain weapon skills, or if you're actually a monk? Hard to say. 

Possibly a non-issue if #740 is fixed, but hard to tell.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Requiring some level of actual martial arts training is probably good.

**Comment by RojjaCebolla** [comment]
if i'm understanding this correctly, unarmed, one-handed, and two-handed all can get a bonus off-hand attack?  does it require TWF / should it?

something something Boots of Kicking mumble mumble...?

**Comment by RikerW** [comment]
As-written, with martial arts as a general skill you have unlocked (vs bare-handed combat, so by default samurai/monks), you can two-weapon with either an empty bare hand (for 2 martial art fists), a one-handed weapon (for a one-handed weapon attack and a martial art fist), or a two-handed weapon (for a normal two-handed weapon attack and a martial art first). It DOES require the ability to two-weapon, and it will train two-weaponing skill just like any normal one-hand wep & one-hand wep two-weaponing.

**Comment by NeroOneTrueKing** [comment]
I think once off-hand punches get no STR damage and reduced Skill damage, the twohanded-weapon + offhand punch strategy will be much more even with a plain twohanded-weapon strategy.
