### ISSUE TITLE
Shift-move into boulders will push the boulder 1 square

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#832]
At least one variant has fixed this, probably should as well

**Comment by RojjaCebolla** [comment]
Maybe this is the fix?  I don't understand the heavy abbreviations in NH code. 🤷‍♀️ 

https://github.com/tsadok/nhfourk/commit/8984cfc6caec2155873221e923cdf6ba7bb78e4a

or this? https://github.com/tsadok/nhfourk/commit/f75c43381bf1668fe34634a5a8dcdce9598ced95
