### ISSUE TITLE
Update repository readme

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dNAO#833]
The repository readme is the same one originally imported from Nethack 3.4.3. It is not descriptive of this repository.

**Comment by mackeyth** [comment]
One thing I would like to know is what flavor of C the code is in. Is there a repository standard?

**Comment by NeroOneTrueKing** [comment]
The repository readme is a duplicate of #501. If someone else is noticing it I guess it needs addressing now.

There isn't a written standard as far as I'm aware, but there are preferred methods. For example, floats and doubles are avoided.
