### ISSUE TITLE
Android QoL

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dNAO#834]
Can we add specific extended commands for android abilities? Having to go through #monster and two menu choices is really tedious.

**Comment by mackeyth** [comment]
Combo is especially bad.
Maybe integrate them as spells?

**Comment by NeroOneTrueKing** [comment]
Ideally, I'd like all commands that go through \#monster also be available as extended commands, so that they can be bound in the rcfile as desired by the player. No ETA on that feature yet

**Comment by Chris-plus-alphanumericgibberish** [comment]
Shift-B or Ctrl-B (for aBilities) both call #monster, which puts combos 3 button presses down.

I'm actually leaning towards a re-arranging things so that those call a new #abilities menu that branches into all existing menus (#power, spells, monster abilities, words of power, #style, #technique, etc.)

I do not believe that powers with different mechanics should be mixed.

**Comment by mackeyth** [comment]
I like Nero's idea of extended commands that the player could keybind as they saw fit. Correct me, but there are extended commands for almost everything that a player can do with the single-keypress commands, right? Is it difficult to add a new extended commands?

**Comment by mackeyth** [comment]
^Z might be better than ^B. Players are used to using z to shoot effects, it's available to yuhjklbn players, ^Z is used for suspend, but not enabled for most public servers.

**Comment by NeroOneTrueKing** [comment]
Using your rcfile, you are able to rebind existing extended commands at will.
Try:
`BINDINGS=^Z:monster`

**Comment by NeroOneTrueKing** [comment]
Added a command to specifically do the android combo (in dev)
#990

**Comment by RikerW** [comment]
I believe this has been fixed with the creation of `#abilities` + `#combo`.
