### ISSUE TITLE
Mirrorblades lost enchantment/artifact damage somewhere

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#835]
They currently only get a base dice substitution. The intended behavior is that mirrorblades add their own enchantment but also the opponent's enchantment, and artifact damage from the reflected weapon as well. Probably lost in xhity.

**Comment by NeroOneTrueKing** [comment]
Hmm, they could temporarily steal the other weapon's enchantment and artifactness. I wonder if that would make messages too weird.

**Comment by Chris-plus-alphanumericgibberish** [comment]
It's intended that the enchantment's stack. I honestly don't remember what they took wrt artifactness. I _don't_ think that a mirrorblade mirroring Vorpal Sword should behead.
