### ISSUE TITLE
Perhaps incorporate Fredriq's changes to peacefuls

### ISSUE THREAD

**Issue by RojjaCebolla** [Chris-plus-alphanumericgibberish/dNAO#837]
The biggest change is causing peacefuls to be *displaced* instead of #chatted or prompted to attack  (both of which are very tiresome in the mines, quest, etc).  Importantly, they're also displaced by hostiles, so that you can't use them to freely escape your pursuers.

some relevant commits:

- bf16fff87bfcf7ad453a521c18c4036c51592232
- https://github.com/FredrIQ/fiqhack/commit/4534c95ab12b87e42a806578622380d9a990c888
- e7efdffa2eea5285300cec2a52b5123be46ea94b
- 77c8871ba612ecde6eaeef128f7197fd2ee0313d
- ead011ab1b19f464db20c474c3bd9dbc6d2d7364
- 554e53ce078cbef0a5cd44e9cd02b107583aea35
- https://github.com/FredrIQ/fiqhack/commit/5943929b300d55d3b13f2032127d54e2e44da2e3
- 8e5e35d2477c5bfe618422320da2763b37db83b5

**Comment by RojjaCebolla** [comment]
i found all of this with a text search, because AFAIK fiq writes good enough commit messages.  but if he didn't say "displace" in a relevant commit, i missed it! https://github.com/FredrIQ/fiqhack/search?p=2&q=displace&type=Commits 

EDIT, oops, here's the correct link for the saerch i used

**Comment by mackeyth** [comment]
Big thumbs up. I just finished a Caveman on NAO, and it is a _staggering_ PITA when a neanderthal manages to get themselves in between the pits on the central defile in the quest home level. It's a problem on the Ranger quest home level, too.

You would want to make sure players can't displace shopkeepers, maybe priests and vault guards, but there are a lot of places where peacefuls can unreasonably limit a players movement options.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Peacefuls are displaced in the current version.
