### ISSUE TITLE
Firework cart explosions crash the game

### ISSUE THREAD

**Issue by AmyBSOD** [Chris-plus-alphanumericgibberish/dNAO#84]
When other monsters are caught in their explosions, the game segfaults and then trying to recover the game says "Strange, that map is not as I remember it", declares a trickery and throws a SIGILL during the trickery handling. This causes the player to lose their savegame with no way to recover it. Probably a double free or corruption issue.

**Comment by RikerW** [comment]
Not just firework carts, gas spores and other explosions seem to cause the same thing. (I can't repro with spheres or fern spores but I can with gas spores).

**Comment by NeroOneTrueKing** [comment]
This seems to have been fixed at some point -- cannot reproduce in dev (Aug 19 2019, version devel 3.18.0).

**Comment by AmyBSOD** [comment]
Nice, I guess it can be closed then :)
