### ISSUE TITLE
Perhaps make the Oracle more interesting and worthwhile

### ISSUE THREAD

**Issue by RojjaCebolla** [Chris-plus-alphanumericgibberish/dNAO#845]
One could incorporate all these variants' little tweaks:

https://nethackwiki.com/wiki/The_Oracle#Variants

https://github.com/FredrIQ/fiqhack/commit/2eeb3a6da7e67424a87c562e342ee4ebc34bfe83

**Comment by Chris-plus-alphanumericgibberish** [comment]
A read through of the existing oracles to make sure there are no factual howlers (I think the Oracle still claims there are wands of wishing, for instance) would also be good.

**Comment by NeroOneTrueKing** [comment]
Fact-checked the oracle's major consultations and the true rumors. False rumors may still be... faulty.

Removing "bug" tag.

**Comment by NeroOneTrueKing** [comment]
Done by Riker in #1384
