### ISSUE TITLE
Objects have colors while blind and un-identified

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#854]
Examples: 
* `blue-glowing vibrosword` (this one is really funny)
* `curved black and gold sword`
* `hard black handmirror`
* `silver pellet`
* `spider-emblemed crossbow` (unless this is inset?)

etc. armor has this problem too

Solutions would either be to make blindness use an intelligent un-identified description, but honestly that's probably overkill. Just make obj->app never refer to colors or anything like that.

**Comment by NeroOneTrueKing** [comment]
OVERKILL IT IS

**Comment by RikerW** [comment]
Not fixed in dev just yet, various artifact descriptions still have this issue.
