### ISSUE TITLE
Spirit power descriptions don't display correctly

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dNAO#860]
When you pull up the spirit power description for Raven's Talons only a short partial message is displayed ("Hugin").

**Comment by RikerW** [comment]
Can't reproduce. 
<img width="842" alt="Screen Shot 2020-06-28 at 7 23 48 PM" src="https://user-images.githubusercontent.com/16050725/85966538-f40c1980-b974-11ea-93a5-388d34fb3676.png">

**Comment by NeroOneTrueKing** [comment]
I can't reproduce using Curses:
![image](https://user-images.githubusercontent.com/28197216/86028692-d3d16e80-b9f7-11ea-9264-2f335d762a15.png)
I can reproduce using TTY. Only the first 5 characters of the first line are printed. UGH.
