### ISSUE TITLE
Consider having pets killed by an engulfing leave partially digested corpses

### ISSUE THREAD

**Issue by lapis413** [Chris-plus-alphanumericgibberish/dNAO#876]
As it stands, a single engulfer can completely kill a pet, especially a mount, and leave no method of recovery. Being able to retrieve a corpse from the monster that killed it so it can be revived would partially prevent this, even if some sort of penalty (lowered health on revive?) would need to be implemented

**Comment by Chris-plus-alphanumericgibberish** [comment]
Digestion attacks do percent-based-damage now: 6f8dda2170b82b6ef81a551a5b59d4b7387cd494
