### ISSUE TITLE
Unable to generate x11tiles

### ISSUE THREAD

**Issue by mindbound** [Chris-plus-alphanumericgibberish/dNAO#89]
Running `tile2x11 monsters.txt objects.txt other.txt` produces an empty file on Arch Linux 4.16.8-1-ARCH x86_64. The culprit seems to be `other.txt`, since omitting it in the above command line produces a valid (although obviously incomplete) file.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Making this compile again would require a very large number of new tiles.  I'm not really in the mood to do pixel art anymore, at least not in the quantities that would be required.  If anyone else is, it would be a useful enhancement.
