### ISSUE TITLE
Add more #tip interactions

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#897]
#tip should do more than just interact with containers.

Some ideas that don't work, given that it's only your inventory and square:
#tip shopkeeper: give them 1 gp if you have it.
#tip rothe: knocks over a sleeping cow, waking it but delaying its next action.

**Comment by NeroOneTrueKing** [comment]
`#tip`, as written, checks the square you are currently on and then prompts for an item from your inventory. 
`#tip`ing in a direction should be prompted after choosing no items from inventory, since it will be least useful.

**Comment by NeroOneTrueKing** [comment]
YASI: funny message on `#tip`ing a fedora

**Comment by Chris-plus-alphanumericgibberish** [comment]
Yeah, I feel like it takes the fun out of it if you're adding a directional prompt just for YAFM.

Tipping the hat is good.
