### ISSUE TITLE
Add a(b)ilities menu

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#906]
Abilities should be the top menu, talking the place of monster a(b)ilities as an alias for #monster.

All the various PC abilities should be accessible from this menu (spells, powers, techniques, styles, monster powers, etc).

**Comment by NeroOneTrueKing** [comment]
I take it that this should be menu of menus:
```
a(b)ilities
 z - spells
 f - spirit powers
 w - words of power
 c - android powers
 c - clockwork powers
 m - monster powers
 s - fighting styles
```

**Comment by NeroOneTrueKing** [comment]
Android / clockwork / monster powers could possibly be directly available in the abilities menu. Hmm.

**Comment by NeroOneTrueKing** [comment]
I'm getting the feeling this will be "rename `#Monster` to `a(b)ilities` and add more things to the list."
Correct me if I'm going about this the wrong way; I'll be getting started on it.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Yup, this is what I had in mind.  It's *possible* that android and clockwork powers should still go under #monster, since they would be conferred by polymorph, but that's not the main way that players interact with them and it's not like it will collide with anything.
