### ISSUE TITLE
Monster melee spells

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#910]
Under some circumstances, monsters with elemental spells seem to be able to cast the melee form of those spells at the player from across the map, without needing line-of-sight.  Observed with mad seers in the Ana home. The exact circumstances are uncertain due to the sheer number of modifiers in play.

**Comment by NeroOneTrueKing** [comment]
Are you sure this issue persists after commit 90c9d9cc6d5a95e9014d37b303b5bf4ba43faaed? I'm not reproducing it in ~5 minutes of testing.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Not 100% sure, but it was the same game that was used to diagnose the other mad-seer-related targeting bug, and I'm _pretty_ sure that I was playing the most-up-to-date version (I was continuing to confirm that the first bug had been cleared up)

**Comment by NeroOneTrueKing** [comment]
Still not reproducing, spent 2000+ turns on Ana home.
