### ISSUE TITLE
Handle the player revisiting a full level

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#922]
The current strategy is "hope it never happens in a real game"

Marked "complex" because what SHOULD happen is difficult to say. Perhaps some monsters could be displaced onto the migrating-monsters chain?

**Comment by NeroOneTrueKing** [comment]
Fixed by https://github.com/Chris-plus-alphanumericgibberish/dNAO/pull/1225 in dev
