### ISSUE TITLE
Alabaster Elves seem to have lost interest in archery

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#934]
They spawn with bows and arrows, but they just walk up to people and smack them with the bow instead of shooting the arrows.  ~~They also don't ever seem to switch off the bows in favor of melee weapons.~~

Update: adding MB_STRONG fixed the issue with them not switching off of bows, but didn't fix the non-use of arrows issue.

**Comment by NeroOneTrueKing** [comment]
Just pulled devel, not reproducing this issue at all.
![image](https://user-images.githubusercontent.com/28197216/86799797-f1c25300-c037-11ea-8fcd-810b064f5741.png)

**Comment by Chris-plus-alphanumericgibberish** [comment]
...They specifically don't fire at Androids.

Tested gnome healer vs. starting Gynoid, they unloaded on the healer but ran into melee with the gynoid.  Perhaps the high starting DR causes them to believe their ranged attack would be useless?
