### ISSUE TITLE
"All items" loops and trap items

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#935]
Is it the case that items in traps aren't part of any other linked list other than the trap they belong to?

If so, how much of the item/artifact detection stuff needs a loop added to deal with trap objects?

I think the blast_element stuff needs one at least.

**Comment by NeroOneTrueKing** [comment]
That's right, they are only part of their trap's linked list.
It makes sense that item/artifact detection should be able to work on them, and it would be an interesting (if confusing at first) method of detecting some kinds of traps. Fortunately it's easy to safely get them all:
```
struct trap * ttmp;
for(ttmp = ftrap; ttmp; ttmp = ttmp->ntrap)
for(obj = ttmp->ammo; obj; obj = obj->nobj)
    /* whatever */;
```

**Comment by NeroOneTrueKing** [comment]
In the spirit of absolute overkill, I am writing a function that returns a pointer to every object, to be used as such:
```
struct obj * otmp;
int owhere = (1<<OBJ_FLOOR)|(1<<OBJ_INVENT)|(1<<OBJ_MINVENT); /* etc; you get the idea */
for (otmp = start_all_objects(owhere); otmp; otmp = next_all_objects(owhere)) {
    /* do things */
}
```

Like with the blasting elements, it will require that whatever is inside the loop not affect the dungeon (making objects change from inside a monster's inventory to on the floor will result in those objects getting missed).

Will also require that whatever is inside the loop not also call `start_all_objects()`. Calling `next_all_objects()` inside the loop would also be a bad idea.


Any further feature requests to it, while it's still in development?

**Comment by NeroOneTrueKing** [comment]
Done, and bugs with it have been fixed once already >_>
