### ISSUE TITLE
Scorpion strike invoke (and possibly others) doesn't anger monsters its used on

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#953]
The code tries to manually approximate the damage. Now that functions like xdamagey exist, it could be shifted to use those? Possibly also the case for other similar invokes, maybe like the various Lordly invokes.

**Comment by Chris-plus-alphanumericgibberish** [comment]
While it would be good to switch artifacts onto an xy format, for now I just added setmangry() calls to the damaging invokes.
