### ISSUE TITLE
Garo or rumor bug?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#970]
I seem to have gotten an empty rumor message from a garo, but it was during a regular game so I couldn't investigate.

**Comment by NeroOneTrueKing** [comment]
Garo, if killed with a clear path to you, always call `outrumor()`. This is a rumor bug.

Looking through rumors.c, it looks like you ought to have gotten an impossible of some sort or your rumor should have been some kind of error message.

**Comment by NeroOneTrueKing** [comment]
Also, any particular reason why you can hear garo give their wisdom even if `!flags.soundok`?

**Comment by Chris-plus-alphanumericgibberish** [comment]
No reason re soundok.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Further details courtesy of a second garo: this is a display problem.  A blank line is displayed when the rumor is given, but it appears in message history (confusingly without the blank line).

**Comment by NeroOneTrueKing** [comment]
Cannot seem to reproduce?
🙏

**Comment by Chris-plus-alphanumericgibberish** [comment]
This is happening reliably on my local game, which suggests that it's something to do with my exact settings or something :( 

I'll switch over to bugfixing again at some point, I'm trying real hard not to die by YASSB at the moment :D

**Comment by Chris-plus-alphanumericgibberish** [comment]
This was caused by windows-style \n\r newlines in my rumors file.
