### ISSUE TITLE
Metroid family of creatures should be vulnerable to cold

### ISSUE THREAD

**Issue by lapis413** [Chris-plus-alphanumericgibberish/dNAO#977]
Cold vulnerability is a major feature of metroids in the source material, along with typically being highly resistant to other attacks. if cold weakness would be too strong consider adding weapon resistance as well (technically they're vulnerable after being hit by cold damage but i don't know how easy that is to code)

**Comment by NeroOneTrueKing** [comment]
Metroids in dnh are all fire resistant and none are cold resistant, so they are already all vulnerable to cold, as much as anything is vulnerable to cold.

Baby and standard metroids already resist blunt damage, and all higher forms of metroids already resist blunt and slashing damage (making them vulnerable to piercing).

At this time, I don't think it would be feasible to cover all sources of cold damage to make sure they properly make metroids vulnerable to physical attacks. *Some* would be, but guaranteeing all of them... not at this time.

**Comment by NeroOneTrueKing** [comment]
Closing because I think the cold-vulnerability flavor is adequately conveyed through the current methods (fire_res, !cold_res), and enhancing it to have a special effect on applying cold damage (especially if metroids become harder to kill without cold!) is not in the cards for a while.
