### ISSUE TITLE
Exercise + Stat-boosting-items interaction

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#983]
While at high stats (including from +stats items), you gain less (and eventually no) positive value from exercise, but still full negative value from abuse.

This makes the player *only* abuse their stats when wearing stat-boosters (like Godhands), which makes them even more dependent on the stat-booster.

In vanilla, stat drain from abuse could be healed up easily. That is no longer the case in dNethack.

Is this a desirable overall effect, or is some change warranted?

**Comment by Chris-plus-alphanumericgibberish** [comment]
After reflecting, the exercise penalty should probably be waved if the current balance of exercise/abuse is negative. That would make most stats easy to maintain but difficult to raise, which is probably the desired vanilla behavior.
