### ISSUE TITLE
Bug in reordering spells?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#999]
It seems that if the first-selected spell has a lower letter than the next selected spell, the spells are not actually swapped.  

If the first-selected spell has a higher letter, they are successfully swapped.

**Comment by NeroOneTrueKing** [comment]
Testing with curses: cannot reproduce
Testing with tty: can reproduce

Investigating further.
